# Generated by Django 4.2.9 on 2025-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_as_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
