# (generated with --quick)

from typing import Any, Iterable, Iterator, List, Tuple

mark: Any
test_parameterized: Any

def DiffListsByKey(iterA: Iterator, iterB: Iterator, keyA, keyB) -> Tuple[list, List[Tuple[Any, Any]], list]: ...
def DiffUnsortedLists(listA: Iterable, listB: Iterable, keyA, keyB) -> Any: ...
def _DiffLists(iterA, iterB, compare) -> Tuple[list, List[Tuple[Any, Any]], list]: ...
def test_diff_lists_by_key() -> None: ...
def test_diff_unsorted_lists() -> None: ...
