# some cursors for pygame
import pygame
NORMAL = pygame.SYSTEM_CURSOR_ARROW
HANDPOINT = pygame.SYSTEM_CURSOR_HAND
RESIZEALL = pygame.SYSTEM_CURSOR_SIZEALL
WAIT = pygame.SYSTEM_CURSOR_WAIT
CROSSHAIR = pygame.SYSTEM_CURSOR_CROSSHAIR