import pennylane as qml
from tqml.tqnet.layers import EFQ as EFQ, PQN as PQN, QDI as QDI, VQ as VQ

def barren_qubits(layer: qml.QNode, qubits_range: range, in_features_range: range = None, depth: int = 10, n: int = 10, variance_threshold: float = 1e-06, return_feedback: bool = False, max_workers: int = 10): ...
def barren_depth(layer: qml.QNode, qubits_range: range, in_features_range: range = None, depth_range: range = ..., n: int = 10, variance_threshold: float = 1e-06, return_feedback: bool = False, max_workers: int = 10): ...
