from _typeshed import Incomplete
from tqml.tqnet._base import QuantumLayer as QuantumLayer

class DepthBothLayer(QuantumLayer):
    n_reuploadings_depth: Incomplete
    n_reuploadings_width: Incomplete
    reuploading_mode_depth: Incomplete
    reuploading_mode_width: Incomplete
    reuploading_order_depth: Incomplete
    n_qubits: Incomplete
    encoding_weights_depth: Incomplete
    encoding_weights_width: Incomplete
    weights: Incomplete
    trainable_frequency: Incomplete
    qnode: Incomplete
    def __init__(self, in_features, n_reuploadings_depth: int = 1, n_reuploadings_width: int = 1, reuploading_mode_depth: str = 'linear', reuploading_mode_width: str = 'linear', reuploading_order_depth: str = 'repeating', depth: int = 1, measurement_mode: str = 'None', rotation: str = 'Z', entangling: str = 'basic', measure: str = 'Y', diff_method: str = 'adjoint', qubit_type: str = 'lightning.qubit', interface: str = 'torch', learn_frequency: bool = False, ranges: str = 'default') -> None: ...
    def extra_repr(self) -> str: ...
    def trainable_layer(self, weights, step: int = 0, id: int = 0) -> None: ...
    def A_repeating(self, x, weights, encoding_weights_depth, encoding_weights_width, index) -> None: ...
    def A_straight(self, x, weights, encoding_weights_width, index) -> None: ...
    def circuit(self, weights, x: Incomplete | None = None, measurement_basis: Incomplete | None = None): ...
    def draw_circuit(self, x: Incomplete | None = None) -> None: ...
    def forward(self, x): ...
