from typing import Callable

def bounce_out(t: float, /) -> float: ...
def in_quad(t: float, /) -> float: ...
def out_quad(t: float, /) -> float: ...
def in_out_quad(t: float, /) -> float: ...
def in_cubic(t: float, /) -> float: ...
def out_cubic(t: float, /) -> float: ...
def in_out_cubic(t: float, /) -> float: ...
def in_quart(t: float, /) -> float: ...
def out_quart(t: float, /) -> float: ...
def in_out_quart(t: float, /) -> float: ...
def in_quint(t: float, /) -> float: ...
def out_quint(t: float, /) -> float: ...
def in_out_quint(t: float, /) -> float: ...
def in_sine(t: float, /) -> float: ...
def out_sine(t: float, /) -> float: ...
def in_out_sine(t: float, /) -> float: ...
def in_expo(t: float, /) -> float: ...
def out_expo(t: float, /) -> float: ...
def in_out_expo(t: float, /) -> float: ...
def in_circ(t: float, /) -> float: ...
def out_circ(t: float, /) -> float: ...
def in_out_circ(t: float, /) -> float: ...
def in_back(t: float, /) -> float: ...
def out_back(t: float, /) -> float: ...
def in_out_back(t: float, /) -> float: ...
def in_elastic(t: float, /) -> float: ...
def out_elastic(t: float, /) -> float: ...
def in_out_elastic(t: float, /) -> float: ...
def in_bounce(t: float, /) -> float: ...
def out_bounce(t: float, /) -> float: ...
def in_out_bounce(t: float, /) -> float: ...

easings: dict[str, Callable]
