class BumpException(Exception): ...


class IncompleteVersionRepresentationException(BumpException): ...


class MissingValueForSerializationException(BumpException): ...


class WorkingDirectoryIsDirtyException(BumpException): ...


class MercurialDoesNotSupportSignedTagsException(BumpException): ...
