# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.nsb2019_hp_durotomy import NSB2019HpDurotomy

class TestNSB2019HpDurotomy(unittest.TestCase):
    """NSB2019HpDurotomy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNSB2019HpDurotomy(self):
        """Test NSB2019HpDurotomy"""
        # inst = NSB2019HpDurotomy()

if __name__ == '__main__':
    unittest.main()
