# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.nsb2019_inj1_retsetting import NSB2019Inj1Retsetting

class TestNSB2019Inj1Retsetting(unittest.TestCase):
    """NSB2019Inj1Retsetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNSB2019Inj1Retsetting(self):
        """Test NSB2019Inj1Retsetting"""
        # inst = NSB2019Inj1Retsetting()

if __name__ == '__main__':
    unittest.main()
