# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.nsb2023_burr2_virus_biosaftey_level_bsl import NSB2023Burr2VirusBiosafteyLevelBsl

class TestNSB2023Burr2VirusBiosafteyLevelBsl(unittest.TestCase):
    """NSB2023Burr2VirusBiosafteyLevelBsl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNSB2023Burr2VirusBiosafteyLevelBsl(self):
        """Test NSB2023Burr2VirusBiosafteyLevelBsl"""
        # inst = NSB2023Burr2VirusBiosafteyLevelBsl()

if __name__ == '__main__':
    unittest.main()
