# Generated by Django 5.2.6 on 2025-09-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_routing_complex', '0002_bgppeergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeer',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_peers', to='dcim.device'),
        ),
    ]
