# Auto-generated by mrtrix3/app.py:print_pydra_code()

import typing
from pathlib import Path  # noqa: F401
from fileformats.generic import FsObject, File, Directory  # noqa: F401
from fileformats.vendor.mrtrix3.medimage import Tracks, ImageIn, ImageOut  # noqa: F401
from pydra.utils.typing import MultiInputObj
from pydra.compose import shell


@shell.define
class Dwi2Response_Dhollander(shell.Task["Dwi2Response_Dhollander.Outputs"]):
    """

    References
    ----------

    * Dhollander, T.; Raffelt, D. & Connelly, A. Unsupervised 3-tissue response function estimation from single-shell or multi-shell diffusion MR data without a co-registered T1 image. ISMRM Workshop on Breaking the Barriers of Diffusion MRI, 2016, 5

    * If -wm_algo option is not used: Dhollander, T.; Mito, R.; Raffelt, D. & Connelly, A. Improved white matter response function estimation for 3-tissue constrained spherical deconvolution. Proc Intl Soc Mag Reson Med, 2019, 555

    Tournier, J.-D.; Smith, R. E.; Raffelt, D.; Tabbara, R.; Dhollander, T.; Pietsch, M.; Christiaens, D.; Jeurissen, B.; Yeh, C.-H. & Connelly, A. MRtrix3: A fast, flexible and open software framework for medical image processing and visualisation. NeuroImage, 2019, 202, 116137

    --------------



    **Author:** Thijs Dhollander (thijs.dhollander@gmail.com)

    **Copyright:** Copyright (c) 2008-2025 the MRtrix3 contributors.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Covered Software is provided under this License on an "as is"
    basis, without warranty of any kind, either expressed, implied, or
    statutory, including, without limitation, warranties that the
    Covered Software is free of defects, merchantable, fit for a
    particular purpose or non-infringing.
    See the Mozilla Public License v. 2.0 for more details.

    For more details, see http://www.mrtrix.org/.

    """

    executable = ("dwi2response", "dhollander")

    in_file: ImageIn = shell.arg(
        position=1,
        argstr="",
        help="Input DWI dataset",
    )
    erode: int | None = shell.arg(
        help="Number of erosion passes to apply to initial (whole brain) mask. Set to 0 to not erode the brain mask. (default: 3)",
        argstr="-erode",
        default=None,
    )
    fa: float | None = shell.arg(
        help="FA threshold for crude WM versus GM-CSF separation. (default: 0.2)",
        argstr="-fa",
        default=None,
    )
    sfwm: float | None = shell.arg(
        help="Final number of single-fibre WM voxels to select, as a percentage of refined WM. (default: 0.5 per cent)",
        argstr="-sfwm",
        default=None,
    )
    gm: float | None = shell.arg(
        help="Final number of GM voxels to select, as a percentage of refined GM. (default: 2 per cent)",
        argstr="-gm",
        default=None,
    )
    csf: float | None = shell.arg(
        help="Final number of CSF voxels to select, as a percentage of refined CSF. (default: 10 per cent)",
        argstr="-csf",
        default=None,
    )
    wm_algo: str | None = shell.arg(
        help="Use external dwi2response algorithm for WM single-fibre voxel selection (options: fa, tax, tournier) (default: built-in Dhollander 2019)",
        allowed_values=["fa", "tax", "tournier"],
        argstr="-wm_algo",
        default=None,
    )
    grad: File | None = shell.arg(
        help="Provide the diffusion gradient table in MRtrix format",
        argstr="-grad",
        default=None,
    )
    fslgrad: File | None = shell.arg(
        help="Provide the diffusion gradient table in FSL bvecs/bvals format",
        argstr="-fslgrad",
        default=None,
    )
    mask: ImageIn | None = shell.arg(
        help="Provide an initial mask for response voxel selection",
        argstr="-mask",
        default=None,
    )
    shells: typing.List[float] | None = shell.arg(
        help="The b-value(s) to use in response function estimation (comma-separated list in case of multiple b-values; b=0 must be included explicitly if desired)",
        argstr="-shells",
        default=None,
    )
    lmax: typing.List[int] | None = shell.arg(
        help="The maximum harmonic degree(s) for response function estimation (comma-separated list in case of multiple b-values)",
        argstr="-lmax",
        default=None,
    )
    nocleanup: bool = shell.arg(
        help="do not delete intermediate files during script execution, and do not delete scratch directory at script completion.",
        argstr="-nocleanup",
        default=False,
    )
    scratch: Directory | None = shell.arg(
        help="manually specify an existing directory in which to generate the scratch directory.",
        argstr="-scratch",
        default=None,
    )
    cont: typing.Any | None = shell.arg(
        help="continue the script from a previous execution; must provide the scratch directory path, and the name of the last successfully-generated file.",
        argstr="-cont",
        default=None,
    )
    info: bool = shell.arg(
        help="display information messages.",
        argstr="-info",
        default=False,
    )
    quiet: bool = shell.arg(
        help="do not display information messages or progress status. Alternatively, this can be achieved by setting the MRTRIX_QUIET environment variable to a non-empty string.",
        argstr="-quiet",
        default=False,
    )
    debug: bool = shell.arg(
        help="display debugging messages.",
        argstr="-debug",
        default=False,
    )
    force: bool = shell.arg(
        help="force overwrite of output files.",
        argstr="-force",
        default=False,
    )
    nthreads: int | None = shell.arg(
        help="use this number of threads in multi-threaded applications (set to 0 to disable multi-threading).",
        argstr="-nthreads",
        default=None,
    )
    config: MultiInputObj[MultiInputObj] | None = shell.arg(
        help="temporarily set the value of an MRtrix config file entry.",
        argstr="-config",
        default=None,
    )
    help: bool = shell.arg(
        help="display this information page and exit.",
        argstr="-help",
        default=False,
    )
    version: bool = shell.arg(
        help="display version information and exit.",
        argstr="-version",
        default=False,
    )

    class Outputs(shell.Outputs):
        out_sfwm: File = shell.outarg(
            position=2,
            argstr="",
            help="Output single-fibre WM response function text file",
            path_template="out_sfwm.txt",
        )
        out_gm: File = shell.outarg(
            position=3,
            argstr="",
            help="Output GM response function text file",
            path_template="out_gm.txt",
        )
        out_csf: File = shell.outarg(
            position=4,
            argstr="",
            help="Output CSF response function text file",
            path_template="out_csf.txt",
        )
        voxels: ImageOut | None = shell.outarg(
            help="Output an image showing the final voxel selection(s)",
            argstr="-voxels",
            default=None,
            path_template="voxels.mif",
        )
