# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NSB2023Behavior(str, Enum):
    """
    Enum class for NSB2023Behavior.
    """

    """
    allowed enum values
    """
    NO = 'No'
    YES = 'Yes'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NSB2023Behavior from a JSON string"""
        return cls(json.loads(json_str))


