# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "SSI Toll Manufacturing",
    "version": "14.0.1.0.0",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "website": "https://github.com/open-synergy/ssi-toll-manufacturing",
    "license": "AGPL-3",
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_mixin",
        "ssi_decorator",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_mrp_production",
        "ssi_product_line_account_mixin",
        "base",
    ],
    "data": [
        "security/ir_module_category/toll_manufacturing_order.xml",
        "security/ir_module_category/batch_toll_manufacturing_order.xml",
        "security/ir_module_category/toll_manufacturing_acceptance.xml",
        "security/ir_module_category/batch_toll_manufacturing_acceptance.xml",
        "security/res_groups/toll_manufacturing_order_type.xml",
        "security/res_groups/toll_manufacturing_order_bom.xml",
        "security/res_groups/toll_manufacturing_order.xml",
        "security/res_groups/batch_toll_manufacturing_acceptance.xml",
        "security/res_groups/batch_toll_manufacturing_order.xml",
        "security/res_groups/toll_manufacturing_acceptance.xml",
        "security/ir_model_access/toll_manufacturing_order_type.xml",
        "security/ir_model_access/toll_manufacturing_order.xml",
        "security/ir_model_access/toll_manufacturing_order_bom.xml",
        "security/ir_model_access/batch_toll_manufacturing_order.xml",
        "security/ir_model_access/toll_manufacturing_acceptance.xml",
        "security/ir_model_access/batch_toll_manufacturing_acceptance.xml",
        "security/ir_rule/toll_manufacturing_order.xml",
        "security/ir_rule/batch_toll_manufacturing_order.xml",
        "security/ir_rule/batch_toll_manufacturing_acceptance.xml",
        "security/ir_rule/toll_manufacturing_acceptance.xml",
        "ir_sequence/toll_manufacturing_order.xml",
        "ir_sequence/batch_toll_manufacturing_order.xml",
        "ir_sequence/batch_toll_manufacturing_acceptance.xml",
        "ir_sequence/toll_manufacturing_acceptance.xml",
        "sequence_template/toll_manufacturing_order.xml",
        "sequence_template/batch_toll_manufacturing_order.xml",
        "sequence_template/batch_toll_manufacturing_acceptance.xml",
        "sequence_template/toll_manufacturing_acceptance.xml",
        "policy_template/batch_toll_manufacturing_order.xml",
        "policy_template/toll_manufacturing_order.xml",
        "policy_template/batch_toll_manufacturing_acceptance.xml",
        "policy_template/toll_manufacturing_acceptance.xml",
        "approval_template/toll_manufacturing_order.xml",
        "approval_template/batch_toll_manufacturing_order.xml",
        "approval_template/batch_toll_manufacturing_acceptance.xml",
        "approval_template/toll_manufacturing_acceptance.xml",
        "menu.xml",
        "views/toll_manufacturing_order_type.xml",
        "views/toll_manufacturing_order_bom.xml",
        "views/toll_manufacturing_order.xml",
        "views/batch_toll_manufacturing_order.xml",
        "views/batch_toll_manufacturing_acceptance.xml",
        "views/toll_manufacturing_acceptance.xml",
    ],
    "demo": [
        "demo/toll_manufacturing_order_type.xml",
        "demo/product_category.xml",
        "demo/product_product.xml",
    ],
    "installable": True,
    "application": False,
}
