from typing import Optional
from datetime import datetime
from pandera.typing import Series
import pandera as pa

from brynq_sdk_functions import BrynQPanderaDataFrameModel

class EmployerGet(BrynQPanderaDataFrameModel):
    """Schema for hr2d__Employer__c entity in HR2Day. Represents an employer record."""

    # Salesforce Standard Fields
    id: Series[str] = pa.Field(alias="Id", nullable=True, coerce=True, description="Record ID")
    name: Series[str] = pa.Field(alias="Name", nullable=True, coerce=True, description="Name employer")
    created_by_id: Series[str] = pa.Field(alias="CreatedById", nullable=True, coerce=True, description="Created By ID")
    created_date: Series[datetime] = pa.Field(alias="CreatedDate", nullable=True, coerce=True, description="Created Date")
    last_activity_date: Optional[Series[datetime]] = pa.Field(alias="LastActivityDate", nullable=True, coerce=True, description="Last Activity Date")
    last_modified_by_id: Series[str] = pa.Field(alias="LastModifiedById", nullable=True, coerce=True, description="Last Modified By ID")
    last_modified_date: Series[datetime] = pa.Field(alias="LastModifiedDate", nullable=True, coerce=True, description="Last Modified Date")
    last_referenced_date: Series[datetime] = pa.Field(alias="LastReferencedDate", nullable=True, coerce=True, description="Last Referenced Date")
    last_viewed_date: Series[datetime] = pa.Field(alias="LastViewedDate", nullable=True, coerce=True, description="Last Viewed Date")
    system_modstamp: Series[datetime] = pa.Field(alias="SystemModstamp", nullable=True, coerce=True, description="System Modstamp")

    # HR2Day Custom Fields
    accruals_si: Series[str] = pa.Field(alias="hr2d__AccrualsSI__c", nullable=True, coerce=True, description="Reservering Opslag SV")
    add_address_line: Series[str] = pa.Field(alias="hr2d__AddAddressLine__c", nullable=True, coerce=True, description="Additional address line")
    admin_bureau: Series[str] = pa.Field(alias="hr2d__AdminBureau__c", nullable=True, coerce=True, description="Admin.Bureau")
    administrator: Series[str] = pa.Field(alias="hr2d__Administrator__c", nullable=True, coerce=True, description="Administrator")
    allowed_delegates_settings: Series[str] = pa.Field(alias="hr2d__AllowedDelegatesSettings__c", nullable=True, coerce=True, description="Toegestane plaatsvervangers")
    annual_leave_from_para_hr_start_date: Series[datetime] = pa.Field(alias="hr2d__AnnualLeaveFromParaHRStartDate__c", nullable=True, coerce=True, description="Collectief verlof uit ParaHR actief per")
    arb_voorw_cluster: Series[str] = pa.Field(alias="hr2d__ArbVoorwCluster__c", nullable=True, coerce=True, description="Empl.conditions group")
    background_color: Series[str] = pa.Field(alias="hr2d__BackgroundColor__c", nullable=True, coerce=True, description="Achtergrond kleur")
    background_id: Series[str] = pa.Field(alias="hr2d__BackgroundID__c", nullable=True, coerce=True, description="AchtergrondID")
    bank: Series[str] = pa.Field(alias="hr2d__Bank__c", nullable=True, coerce=True, description="Bank account")
    bank_bic: Series[str] = pa.Field(alias="hr2d__BankBIC__c", nullable=True, coerce=True, description="Bank-BIC")
    bank_fields: Series[str] = pa.Field(alias="hr2d__BankFields__c", nullable=True, coerce=True, description="Bank-fields")
    bank_iban: Series[str] = pa.Field(alias="hr2d__BankIBAN__c", nullable=True, coerce=True, description="Bank-IBAN")
    banner_id: Series[str] = pa.Field(alias="hr2d__BannerID__c", nullable=True, coerce=True, description="BannerID")
    banner_mobile_id: Series[str] = pa.Field(alias="hr2d__BannerMobileID__c", nullable=True, coerce=True, description="BannerMobileID")
    banner_mobile_position: Series[str] = pa.Field(alias="hr2d__BannerMobilePosition__c", nullable=True, coerce=True, description="Banner position on mobile")
    banner_position: Series[str] = pa.Field(alias="hr2d__BannerPosition__c", nullable=True, coerce=True, description="Banner position")
    batch_size: Series[str] = pa.Field(alias="hr2d__BatchSize__c", nullable=True, coerce=True, description="BatchSize")
    benefits_settings: Series[str] = pa.Field(alias="hr2d__BenefitsSettings__c", nullable=True, coerce=True, description="Instellingen Benefits")
    billing_user: Series[str] = pa.Field(alias="hr2d__BillingUser__c", nullable=True, coerce=True, description="User for billing")
    bi_settings: Series[str] = pa.Field(alias="hr2d__BiSettings__c", nullable=True, coerce=True, description="Instellingen BI")
    brand_color: Series[str] = pa.Field(alias="hr2d__BrandColor__c", nullable=True, coerce=True, description="Huisstijl kleur")
    city: Series[str] = pa.Field(alias="hr2d__City__c", nullable=True, coerce=True, description="City")
    coc_nr: Series[str] = pa.Field(alias="hr2d__CoCNr__c", nullable=True, coerce=True, description="CoC number")
    competence_classifications: Series[str] = pa.Field(alias="hr2d__CompetenceClassifications__c", nullable=True, coerce=True, description="Competentieclassificaties")
    competence_settings: Series[str] = pa.Field(alias="hr2d__CompetenceSettings__c", nullable=True, coerce=True, description="Instellingen Competenties")
    concern_employer: Series[str] = pa.Field(alias="hr2d__ConcernEmployer__c", nullable=True, coerce=True, description="Linked to (concern)employer")
    config_employer: Series[str] = pa.Field(alias="hr2d__ConfigEmployer__c", nullable=True, coerce=True, description="Linked to configemployer")
    contact_person: Series[str] = pa.Field(alias="hr2d__ContactPerson__c", nullable=True, coerce=True, description="Contactperson")
    contact_setting: Series[str] = pa.Field(alias="hr2d__ContactSetting__c", nullable=True, coerce=True, description="Contact settings")
    control_rep_email: Series[str] = pa.Field(alias="hr2d__ControlRepEmail__c", nullable=True, coerce=True, description="Controlerapport e-mail")
    control_rep_run_nr: Series[float] = pa.Field(alias="hr2d__ControlRepRunNr__c", nullable=True, coerce=True, description="Controlerapport runnr")
    converted_to_content_documents: Series[str] = pa.Field(alias="hr2d__ConvertedToContentDocuments__c", nullable=True, coerce=True, description="Geconverteerd naar contentdocuments")
    corporate_identity: Series[str] = pa.Field(alias="hr2d__CorporateIdentity__c", nullable=True, coerce=True, description="Corporate identity")
    country: Series[str] = pa.Field(alias="hr2d__Country__c", nullable=True, coerce=True, description="Country")
    document_categories: Series[str] = pa.Field(alias="hr2d__DocumentCategories__c", nullable=True, coerce=True, description="Documentcategorieën")
    document_groups: Series[str] = pa.Field(alias="hr2d__DocumentGroups__c", nullable=True, coerce=True, description="Document groups")
    document_signflow_settings: Series[str] = pa.Field(alias="hr2d__DocumentSignflowSettings__c", nullable=True, coerce=True, description="Document signflow settings")
    education_classifications: Series[str] = pa.Field(alias="hr2d__EducationClassifications__c", nullable=True, coerce=True, description="Opleidingsclassificaties")
    education_reasons: Series[str] = pa.Field(alias="hr2d__EducationReasons__c", nullable=True, coerce=True, description="Opleidingredenen")
    education_statuses: Series[str] = pa.Field(alias="hr2d__EducationStatuses__c", nullable=True, coerce=True, description="Opleidingsstatussen")
    education_types: Series[str] = pa.Field(alias="hr2d__EducationTypes__c", nullable=True, coerce=True, description="Opleidingstypes")
    eic_panels: Series[str] = pa.Field(alias="hr2d__EIC_Panels__c", nullable=True, coerce=True, description="EIC Panelen")
    eic_settings: Series[str] = pa.Field(alias="hr2d__EIC_Settings__c", nullable=True, coerce=True, description="EIC Settings")
    eic_panels_old: Series[str] = pa.Field(alias="hr2d__EicPanels__c", nullable=True, coerce=True, description="EIC Panelen (vervallen)")
    eic_settings_old: Series[str] = pa.Field(alias="hr2d__EicSettings__c", nullable=True, coerce=True, description="EIC Settings (vervallen)")
    email: Series[str] = pa.Field(alias="hr2d__Email__c", nullable=True, coerce=True, description="Email")
    email_cc: Series[str] = pa.Field(alias="hr2d__Email_cc__c", nullable=True, coerce=True, description="Email cc")
    email_fin_adm: Series[str] = pa.Field(alias="hr2d__Email_FinAdm__c", nullable=True, coerce=True, description="Email Fin.Adm.")
    empl_nr_options: Series[str] = pa.Field(alias="hr2d__EmplNrOptions__c", nullable=True, coerce=True, description="Personeelsnummer opties")
    employer_group: Series[str] = pa.Field(alias="hr2d__EmployerGroup__c", nullable=True, coerce=True, description="Werkgeversgroep")
    employer_nr: Series[str] = pa.Field(alias="hr2d__EmployerNr__c", nullable=True, coerce=True, description="Werkgevernr waardereeks")
    employer_nr_keys: Series[str] = pa.Field(alias="hr2d__EmployerNrKeys__c", nullable=True, coerce=True, description="Werkgevernr sleutels")
    equipment_attributes: Series[str] = pa.Field(alias="hr2d__EquipmentAttributes__c", nullable=True, coerce=True, description="Bedrijfsmiddel kenmerken")
    equipment_categories: Series[str] = pa.Field(alias="hr2d__EquipmentCategories__c", nullable=True, coerce=True, description="Bedrijfsmiddel categorieën")
    equipment_types: Series[str] = pa.Field(alias="hr2d__EquipmentTypes__c", nullable=True, coerce=True, description="Bedrijfsmiddel types")
    external: Series[str] = pa.Field(alias="hr2d__External__c", nullable=True, coerce=True, description="Employer with external employees")
    feature_toggles: Series[str] = pa.Field(alias="hr2d__FeatureToggles__c", nullable=True, coerce=True, description="Features")
    fin_adm_id: Series[str] = pa.Field(alias="hr2d__FinAdmID__c", nullable=True, coerce=True, description="Financial Admin. ID")
    fin_settings: Series[str] = pa.Field(alias="hr2d__FinSettings__c", nullable=True, coerce=True, description="Instellingen Betaling/Journaalpost")
    full_name: Series[str] = pa.Field(alias="hr2d__FullName__c", nullable=True, coerce=True, description="Full name")
    grant_access_days_before: Series[float] = pa.Field(alias="hr2d__GrantAccessDaysBefore__c", nullable=True, coerce=True, description="Access before (days)")
    grootboek_rek_schema: Series[str] = pa.Field(alias="hr2d__GrootboekRekSchema__c", nullable=True, coerce=True, description="Ledger chart of accounts")
    header_settings: Series[str] = pa.Field(alias="hr2d__HeaderSettings__c", nullable=True, coerce=True, description="Koptekst")
    house_nr: Series[float] = pa.Field(alias="hr2d__HouseNr__c", nullable=True, coerce=True, description="House number")
    house_nr_add: Series[str] = pa.Field(alias="hr2d__HouseNrAdd__c", nullable=True, coerce=True, description="House number add.")
    inbox_enabled: Series[bool] = pa.Field(alias="hr2d__InboxEnabled__c", nullable=True, coerce=True, description="Inbox functionaliteiten ingeschakeld")
    is_concern_employer: Series[bool] = pa.Field(alias="hr2d__IsConcernEmployer__c", nullable=True, coerce=True, description="Is only concernemployer")
    is_config_employer: Series[bool] = pa.Field(alias="hr2d__IsConfigEmployer__c", nullable=True, coerce=True, description="Is only configemployer")
    journal_code: Series[str] = pa.Field(alias="hr2d__JournalCode__c", nullable=True, coerce=True, description="Journal code")
    leave_recalculation_settings: Series[str] = pa.Field(alias="hr2d__LeaveRecalculationSettings__c", nullable=True, coerce=True, description="Instellingen voor herrekenen verlof")
    leave_settings: Series[str] = pa.Field(alias="hr2d__LeaveSettings__c", nullable=True, coerce=True, description="Instellingen Verlof")
    locations: Series[str] = pa.Field(alias="hr2d__Locations__c", nullable=True, coerce=True, description="Locaties")
    logo: Series[str] = pa.Field(alias="hr2d__Logo__c", nullable=True, coerce=True, description="Logo")
    logo_eic_id: Series[str] = pa.Field(alias="hr2d__LogoEicID__c", nullable=True, coerce=True, description="LogoEicID")
    logo_id: Series[str] = pa.Field(alias="hr2d__LogoID__c", nullable=True, coerce=True, description="LogoID")
    logo_url: Series[str] = pa.Field(alias="hr2d__LogoUrl__c", nullable=True, coerce=True, description="Logo (externe url)")
    lwc_eic_panels_layout: Series[str] = pa.Field(alias="hr2d__LWC_EIC_PanelsLayout__c", nullable=True, coerce=True, description="EIC Panelen")
    lwc_hic_panels_layout: Series[str] = pa.Field(alias="hr2d__LWC_HIC_PanelsLayout__c", nullable=True, coerce=True, description="HIC Panelen")
    lwc_mic_panels_layout: Series[str] = pa.Field(alias="hr2d__LWC_MIC_PanelsLayout__c", nullable=True, coerce=True, description="MIC Panelen")
    maintain_historical_data: Series[str] = pa.Field(alias="hr2d__MaintainHistoricalData__c", nullable=True, coerce=True, description="Verlofgegevens per kalenderjaar miv jaar")
    mic_panels: Series[str] = pa.Field(alias="hr2d__MIC_Panels__c", nullable=True, coerce=True, description="MIC Panelen")
    mic_settings: Series[str] = pa.Field(alias="hr2d__MIC_Settings__c", nullable=True, coerce=True, description="MIC Settings")
    mic_panels_old: Series[str] = pa.Field(alias="hr2d__MicPanels__c", nullable=True, coerce=True, description="MIC Panelen (vervallen)")
    mic_settings_old: Series[str] = pa.Field(alias="hr2d__MicSettings__c", nullable=True, coerce=True, description="Instellingen tonen afdeling en functie")
    next_empl_nr: Series[float] = pa.Field(alias="hr2d__NextEmplNr__c", nullable=True, coerce=True, description="Next employee number")
    notifications: Series[str] = pa.Field(alias="hr2d__Notifications__c", nullable=True, coerce=True, description="Notificaties")
    pay_day: Series[float] = pa.Field(alias="hr2d__PayDay__c", nullable=True, coerce=True, description="Payment day")
    payroll_archive_year: Series[str] = pa.Field(alias="hr2d__PayrollArchiveYear__c", nullable=True, coerce=True, description="Payroll archief jaar")
    payroll_cycle: Series[str] = pa.Field(alias="hr2d__PayrollCycle__c", nullable=True, coerce=True, description="Payroll cycle")
    payroll_detect_settings: Series[str] = pa.Field(alias="hr2d__PayrollDetectSettings__c", nullable=True, coerce=True, description="Instellingen PayrollDetect")
    payroll_recalc: Series[str] = pa.Field(alias="hr2d__PayrollRecalc__c", nullable=True, coerce=True, description="Payroll TWK vorig jaar")
    payroll_set: Series[str] = pa.Field(alias="hr2d__PayrollSet__c", nullable=True, coerce=True, description="Payroll set")
    payroll_settings: Series[str] = pa.Field(alias="hr2d__PayrollSettings__c", nullable=True, coerce=True, description="Instellingen Payroll")
    payroll_start_date: Series[datetime] = pa.Field(alias="hr2d__PayrollStartDate__c", nullable=True, coerce=True, description="Payroll oudste TWK datum")
    payslip_mail_text: Series[str] = pa.Field(alias="hr2d__PayslipMailText__c", nullable=True, coerce=True, description="Payslip email text")
    payslip_name_format: Series[str] = pa.Field(alias="hr2d__PayslipNameFormat__c", nullable=True, coerce=True, description="Loonstrook naamopmaak")
    payslip_settings: Series[str] = pa.Field(alias="hr2d__PayslipSettings__c", nullable=True, coerce=True, description="Instellingen Salarisspecificaties")
    payslip_standard_text: Series[str] = pa.Field(alias="hr2d__PayslipStandardText__c", nullable=True, coerce=True, description="Payslip text")
    payslip_text: Series[str] = pa.Field(alias="hr2d__PayslipText__c", nullable=True, coerce=True, description="Payslip text")
    pens_id: Series[str] = pa.Field(alias="hr2d__PensId__c", nullable=True, coerce=True, description="Pension fund number")
    performance_settings: Series[str] = pa.Field(alias="hr2d__PerformanceSettings__c", nullable=True, coerce=True, description="Instellingen Performance Management")
    period_nr: Series[float] = pa.Field(alias="hr2d__PeriodNr__c", nullable=True, coerce=True, description="Period")
    phone: Series[str] = pa.Field(alias="hr2d__Phone__c", nullable=True, coerce=True, description="Phone")
    phone2: Series[str] = pa.Field(alias="hr2d__Phone2__c", nullable=True, coerce=True, description="Phone 2")
    portfolio_setting: Series[str] = pa.Field(alias="hr2d__PortfolioSetting__c", nullable=True, coerce=True, description="Instellingen Portfolio")
    postal_code: Series[str] = pa.Field(alias="hr2d__PostalCode__c", nullable=True, coerce=True, description="Postal code")
    qualification_attributes: Series[str] = pa.Field(alias="hr2d__QualificationAttributes__c", nullable=True, coerce=True, description="Kwalificatie kenmerken")
    qualification_categories: Series[str] = pa.Field(alias="hr2d__QualificationCategories__c", nullable=True, coerce=True, description="Kwalificatie categorieën")
    qualification_level_options: Series[str] = pa.Field(alias="hr2d__QualificationLevelOptions__c", nullable=True, coerce=True, description="Kwalificatieniveau opties")
    qualification_levels: Series[str] = pa.Field(alias="hr2d__QualificationLevels__c", nullable=True, coerce=True, description="Bevoegdheidsniveaus")
    qualification_types: Series[str] = pa.Field(alias="hr2d__QualificationTypes__c", nullable=True, coerce=True, description="Kwalificatie types")
    record_id: Series[str] = pa.Field(alias="hr2d__RecordId__c", nullable=True, coerce=True, description="Record-id (lang)")
    revoke_access_after_days: Series[float] = pa.Field(alias="hr2d__RevokeAccessAfterDays__c", nullable=True, coerce=True, description="Revoke access after (days)")
    revoke_approver_access_after_days: Series[float] = pa.Field(alias="hr2d__RevokeApproverAccessAfterDays__c", nullable=True, coerce=True, description="Revoke approver access after (days)")
    roles: Series[str] = pa.Field(alias="hr2d__Roles__c", nullable=True, coerce=True, description="Rollen")
    sharing_settings: Series[str] = pa.Field(alias="hr2d__SharingSettings__c", nullable=True, coerce=True, description="Autorisatie-instellingen")
    sharing_settings_department_scope: Series[str] = pa.Field(alias="hr2d__SharingSettingsDepartmentScope__c", nullable=True, coerce=True, description="Autorisatie-instellingen voor afdeling")
    short_name: Series[str] = pa.Field(alias="hr2d__ShortName__c", nullable=True, coerce=True, description="Short name")
    sick_classifications: Series[str] = pa.Field(alias="hr2d__SickClassifications__c", nullable=True, coerce=True, description="Verzuimclassificaties")
    sick_leave_settings: Series[str] = pa.Field(alias="hr2d__SickLeaveSettings__c", nullable=True, coerce=True, description="Instellingen Verzuim")
    sick_leave_start_date: Series[datetime] = pa.Field(alias="hr2d__SickLeaveStartDate__c", nullable=True, coerce=True, description="Verzuimmodule actief per")
    sso_mail_text: Series[str] = pa.Field(alias="hr2d__SSOMailText__c", nullable=True, coerce=True, description="Mail uitdienst SSO")
    status: Series[str] = pa.Field(alias="hr2d__Status__c", nullable=True, coerce=True, description="Status")
    street: Series[str] = pa.Field(alias="hr2d__Street__c", nullable=True, coerce=True, description="Street")
    tax_cycle: Series[str] = pa.Field(alias="hr2d__TaxCycle__c", nullable=True, coerce=True, description="Alternate tax cycle")
    tax_id: Series[str] = pa.Field(alias="hr2d__TaxId__c", nullable=True, coerce=True, description="Tax id (Loonheffingennummer)")
    text_style: Series[str] = pa.Field(alias="hr2d__TextStyle__c", nullable=True, coerce=True, description="Tekststijl")
    update_leave_entitlements: Series[str] = pa.Field(alias="hr2d__UpdateLeaveEntitlements__c", nullable=True, coerce=True, description="Verlofrechten autom. bijwerken miv jaar")
    user_termination_settings: Series[str] = pa.Field(alias="hr2d__UserTerminationSettings__c", nullable=True, coerce=True, description="Instellingen gebruikers uitdienst")
    uwv_contact: Series[str] = pa.Field(alias="hr2d__UWVContact__c", nullable=True, coerce=True, description="UWV Contactperson")
    vervangingen_enabled: Series[str] = pa.Field(alias="hr2d__VervangingenEnabled__c", nullable=True, coerce=True, description="Vervangingen activeren")
    wage_type_details: Series[str] = pa.Field(alias="hr2d__WageTypeDetails__c", nullable=True, coerce=True, description="Looncomp details")
    werk_kosten_regeling: Series[str] = pa.Field(alias="hr2d__WerkKostenRegeling__c", nullable=True, coerce=True, description="Werkkostenregeling")
    year: Series[str] = pa.Field(alias="hr2d__Year__c", nullable=True, coerce=True, description="Year")

    class _Annotation:
        """Annotation class for primary and foreign keys"""
        primary_key = "id"
        foreign_keys = {}

    class Config:
        """Schema configuration"""
        strict = "filter"  # Allow extra columns not defined in schema
        coerce = True
        add_missing_columns = True  # Add missing columns as nullable
