from _typeshed import Incomplete

AZURE_OPENAI_URL_SUFFIX: str
DOCUMENT_MIME_TYPES: Incomplete
GOOGLE_SCOPES: Incomplete
GRPC_ENABLE_RETRIES_KEY: str
INVOKER_PROPAGATED_MAX_RETRIES: int
INVOKER_DEFAULT_TIMEOUT: float
HEX_REPR_LENGTH: int
OPENAI_DEFAULT_URL: str
SECONDS_TO_MILLISECONDS: int
