# coding: utf-8
# Generated by Django 2.2.3 on 2019-12-19 07:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('get_data', '0002_auto_20161209_1332'), ]

    operations = [
        migrations.AlterModelOptions(
            name='getdatasession',
            options={
                'verbose_name': 'Сессия обмена данными',
                'verbose_name_plural': 'Сессии обмена данными'
            }, ),
        migrations.AlterModelOptions(
            name='getdatastatistic',
            options={
                'verbose_name': 'Статистика сессии обмена данными',
                'verbose_name_plural': 'Статистика сессий обмена данными'
            }, ),
    ]
