from _typeshed import Incomplete
from tqml.tqnet._base import QuantumLayer as QuantumLayer
from tqml.tqnet.exceptions import DimensionException as DimensionException

class PQN(QuantumLayer):
    q_layers: Incomplete
    qnode: Incomplete
    weights: Incomplete
    trainable_frequency: Incomplete
    def __init__(self, in_features, n_qubits, depth: int = 1, measurement_mode: str = 'None', rotation: str = 'X', entangling: str = 'strong', measure: str = 'Y', diff_method: str = 'adjoint', qubit_type: str = 'lightning.qubit', interface: str = 'torch', learn_frequency: bool = False, ranges: str = 'default') -> None: ...
    def extra_repr(self) -> str: ...
    def circuit(self, weights, x, measurement_basis: Incomplete | None = None): ...
    def forward(self, x): ...
    def draw_circuit(self) -> None: ...
    def get_quantum_tape(self, x, weights: Incomplete | None = None): ...
