"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userprofile import UserProfile, UserProfileTypedDict
from egain_api_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UserProfilesTypedDict(TypedDict):
    r"""Success"""

    profile: NotRequired[List[UserProfileTypedDict]]
    r"""User profiles assigend to user."""


class UserProfiles(BaseModel):
    r"""Success"""

    profile: Optional[List[UserProfile]] = None
    r"""User profiles assigend to user."""
