key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEINJgRPA04ePuXOw2n+nYcg+RycZ+xZJLlTBNDUmCIocToAoGCCqGSM49
AwEHoUQDQgAEpmbttSWJouIJzfJbZE65NP1ENBsqSiTAWS20LDvkLyYDAAKHJ5Sg
ppTu9Or5LRsvswxflEQCdXguMoSebJ1KXg==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6TCCAY8CFFMS/4zt8Er+it0GilKNr5z+JumGMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTEwMTExMzQ5MzhaFw0zNTEwMDkxMzQ5
MzhaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABKZm7bUliaLiCc3yW2ROuTT9RDQbKkokwFkttCw75C8mAwAChyeUoKaU
7vTq+S0bL7MMX5REAnV4LjKEnmydSl4wCgYIKoZIzj0EAwIDSAAwRQIgCyyayA86
q1RCUtEs4qQXf4DuMHb+y5hLYjSHIm+kEIACIQDyflQToona8Aodd1Z+a3LKkExE
NtPJ1Kb4S+xaX6yIbw==
-----END CERTIFICATE-----
"""