# Generated by Django 5.2.6 on 2025-09-30 14:57

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('ipam', '0082_add_prefix_network_containment_indexes'),
        ('netbox_routing_complex', '0004_alter_bgppeer_device'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('vnid', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vnis', to='tenancy.tenant')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vnis', to='ipam.vlan')),
            ],
            options={
                'ordering': ('vnid',),
                'unique_together': {('vlan', 'vnid')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VXLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('l3mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('ingress_replication', models.BooleanField(default=True)),
                ('ipv4_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.ipaddress')),
                ('ipv6_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vxlan', to='netbox_routing_complex.vni')),
            ],
            options={
                'ordering': ('vni',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
