# Generated by Django 5.2.6 on 2025-09-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing_complex', '0005_vni_vxlan'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vni',
            unique_together={('vnid', 'tenant')},
        ),
    ]
