# Generated by Django 5.2.6 on 2025-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing_complex', '0010_staticroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='subnet',
            field=models.CharField(max_length=100),
        ),
    ]
