"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SchemasTagsTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Tag Category ID"""
    tags: NotRequired[List[str]]


class SchemasTags(BaseModel):
    id: Optional[str] = None
    r"""Tag Category ID"""

    tags: Optional[List[str]] = None
