"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .link import Link, LinkTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserViewTypedDict(TypedDict):
    link: NotRequired[List[LinkTypedDict]]
    r"""The link to the user."""
    first_name: NotRequired[str]
    r"""The first name of the user."""
    last_name: NotRequired[str]
    r"""The last name of the user."""
    id: NotRequired[str]
    r"""The ID of the user."""


class UserView(BaseModel):
    link: Optional[List[Link]] = None
    r"""The link to the user."""

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None
    r"""The first name of the user."""

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None
    r"""The last name of the user."""

    id: Optional[str] = None
    r"""The ID of the user."""
