# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_async_client.models.nsb2023_behavior_destination import NSB2023BehaviorDestination

class TestNSB2023BehaviorDestination(unittest.TestCase):
    """NSB2023BehaviorDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNSB2023BehaviorDestination(self):
        """Test NSB2023BehaviorDestination"""
        # inst = NSB2023BehaviorDestination()

if __name__ == '__main__':
    unittest.main()
