from _typeshed import Incomplete
from tqml.tqnet._base import QuantumLayer as QuantumLayer

class DepthLayer(QuantumLayer):
    n_qubits: int
    weights: Incomplete
    trainable_frequency: Incomplete
    qnode: Incomplete
    def __init__(self, in_features, depth: int = 1, rotation: str = 'Z', entangling: str = 'basic', measure: str = 'Y', diff_method: str = 'adjoint', qubit_type: str = 'lightning.qubit', interface: str = 'torch', learn_frequency: bool = False, ranges: str = 'default') -> None: ...
    def extra_repr(self) -> str: ...
    def circuit(self, weights, x: Incomplete | None = None, measurement_basis: Incomplete | None = None): ...
    def draw_circuit(self, x: Incomplete | None = None) -> None: ...
    def forward(self, x): ...
