# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Risk Limit",
    "version": "14.0.3.3.0",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "website": "https://simetri-sinergi.id",
    "license": "AGPL-3",
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_financial_accounting",
        "ssi_transaction_partner_mixin",
        "ssi_res_partner_m2o_configurator_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_partner",
        "base_automation",
        "queue_job_batch",
    ],
    "data": [
        "security/ir_module_category/risk_limit_assignment_module_category.xml",
        "security/ir_module_category/risk_limit_batch_assignment_module_category.xml",
        "security/res_groups.xml",
        "security/res_groups/risk_limit_assignment.xml",
        "security/res_groups/risk_limit_batch_assignment.xml",
        "security/ir_model_access/risk_limit_item.xml",
        "security/ir_model_access/risk_limit_type.xml",
        "security/ir_model_access/risk_limit_assignment.xml",
        "security/ir_model_access/risk_limit_batch_assignment.xml",
        "security/ir_model_access/partner_risk_limit.xml",
        "security/ir_model_access/create_risk_limit_assignment.xml",
        "security/ir_rule/risk_limit_assignment.xml",
        "security/ir_rule/risk_limit_batch_assignment.xml",
        "ir_sequence/risk_limit_assignment.xml",
        "ir_sequence/risk_limit_batch_assignment.xml",
        "policy_template/risk_limit_assignment.xml",
        "policy_template/risk_limit_batch_assignment.xml",
        "sequence_template/risk_limit_assignment.xml",
        "sequence_template/risk_limit_batch_assignment.xml",
        "approval_template/risk_limit_assignment.xml",
        "approval_template/risk_limit_batch_assignment.xml",
        "data/ir_actions_server_data.xml",
        "data/base_automation_data.xml",
        "menu.xml",
        "wizards/create_risk_limit_assignment.xml",
        "views/risk_limit_item_views.xml",
        "views/risk_limit_type_views.xml",
        "views/risk_limit_assignment_views.xml",
        "views/risk_limit_batch_assignment_views.xml",
        "views/res_partner_views.xml",
    ],
    "demo": [
        "demo/risk_limit_item.xml",
        "demo/risk_limit_type.xml",
    ],
    "application": False,
}
