"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


OptionalArticleAttributes = Literal[
    "articleMacro",
    "availabilityDate",
    "averageRating",
    "contentText",
    "orderNumber",
    "suggestionType",
    "timesRated",
    "availableEditions",
    "articleTypeAttributes",
    "milestone",
    "all",
]
r"""The fields of the article to be returned."""
