"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paginationinfo import PaginationInfo, PaginationInfoTypedDict
from .portal import Portal, PortalTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PortalResultTypedDict(TypedDict):
    r"""Success"""

    portal: NotRequired[List[PortalTypedDict]]
    r"""portals"""
    pagination_info: NotRequired[PaginationInfoTypedDict]


class PortalResult(BaseModel):
    r"""Success"""

    portal: Optional[List[Portal]] = None
    r"""portals"""

    pagination_info: Annotated[
        Optional[PaginationInfo], pydantic.Field(alias="paginationInfo")
    ] = None
