"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .paginationinfo import PaginationInfo, PaginationInfoTypedDict
from .quickpickresult import QuickpickResult, QuickpickResultTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QuickpickResultsTypedDict(TypedDict):
    r"""Success"""

    quickpick: NotRequired[List[QuickpickResultTypedDict]]
    r"""quick picks"""
    pagination_info: NotRequired[PaginationInfoTypedDict]


class QuickpickResults(BaseModel):
    r"""Success"""

    quickpick: Optional[List[QuickpickResult]] = None
    r"""quick picks"""

    pagination_info: Annotated[
        Optional[PaginationInfo], pydantic.Field(alias="paginationInfo")
    ] = None
