from .cpu_scheduling_algorithm import fcfs_scheduling, sjf_scheduling_non_preemptive, srtn_scheduling_preemptive, priority_scheduling_non_preemptive, priority_scheduling_preemptive
from .file_allocation_method import SequentialFileAllocation
from .page_replacement_algorithm import lru_page_replacement, fifo_page_replacement