"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GetHealthStatusResponseTypedDict(TypedDict):
    r"""Health status"""

    status: NotRequired[str]


class GetHealthStatusResponse(BaseModel):
    r"""Health status"""

    status: Optional[str] = None
