# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is Similarity Search Engine for executable binaries

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.base_response_nearest_neighbor_analysis import BaseResponseNearestNeighborAnalysis

class TestBaseResponseNearestNeighborAnalysis(unittest.TestCase):
    """BaseResponseNearestNeighborAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponseNearestNeighborAnalysis:
        """Test BaseResponseNearestNeighborAnalysis
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponseNearestNeighborAnalysis`
        """
        model = BaseResponseNearestNeighborAnalysis()
        if include_optional:
            return BaseResponseNearestNeighborAnalysis(
                status = True,
                data = {
                    'key' : {
                        'key' : revengai.models.nearest_neighbor.NearestNeighbor(
                            distance = 1.337, 
                            nearest_neighbor_analysis_id = 56, 
                            nearest_neighbor_analysis_name = '', 
                            nearest_neighbor_function_name = '', 
                            nearest_neighbor_function_name_mangled = '', 
                            nearest_neighbor_binary_id = 56, 
                            nearest_neighbor_sha_256_hash = '', 
                            nearest_neighbor_debug = True, )
                        }
                    },
                message = '',
                errors = [
                    revengai.models.error_model.ErrorModel(
                        code = '', 
                        message = '', )
                    ],
                meta = revengai.models.meta_model.MetaModel(
                    pagination = revengai.models.pagination_model.PaginationModel(
                        page_size = 56, 
                        page_number = 56, 
                        has_next_page = True, ), )
            )
        else:
            return BaseResponseNearestNeighborAnalysis(
        )
        """

    def testBaseResponseNearestNeighborAnalysis(self):
        """Test BaseResponseNearestNeighborAnalysis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
