import platform

WOW_PROCESS_NAME = "Wow.exe"
OS_SYSTEM = platform.system()

# Navigation
WORLD_TILE_SIZE = 533.333
MAX_MAP_AXIS_LENGTH = 32
MAX_MAP_COORDINATE = WORLD_TILE_SIZE * MAX_MAP_AXIS_LENGTH
MINIMAP_TILE_SIZE = 256
