depends = ('ITKPyBase', 'ITKCommon', )
templates = (  ('CudaDataManager', 'itk::CudaDataManager', 'itkCudaDataManager', True),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUC2', True, 'unsigned char, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUC3', True, 'unsigned char, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUC4', True, 'unsigned char, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUL2', True, 'unsigned long, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUL3', True, 'unsigned long, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUL4', True, 'unsigned long, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageSS2', True, 'signed short, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageSS3', True, 'signed short, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageSS4', True, 'signed short, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUS2', True, 'unsigned short, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUS3', True, 'unsigned short, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageUS4', True, 'unsigned short, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageF2', True, 'float, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF22', True, 'itk::Vector< float,2 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF22', True, 'itk::CovariantVector< float,2 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF32', True, 'itk::Vector< float,3 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF32', True, 'itk::CovariantVector< float,3 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF42', True, 'itk::Vector< float,4 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF42', True, 'itk::CovariantVector< float,4 >, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageF3', True, 'float, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF23', True, 'itk::Vector< float,2 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF23', True, 'itk::CovariantVector< float,2 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF33', True, 'itk::Vector< float,3 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF33', True, 'itk::CovariantVector< float,3 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF43', True, 'itk::Vector< float,4 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF43', True, 'itk::CovariantVector< float,4 >, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageF4', True, 'float, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF24', True, 'itk::Vector< float,2 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF24', True, 'itk::CovariantVector< float,2 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF34', True, 'itk::Vector< float,3 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF34', True, 'itk::CovariantVector< float,3 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageVF44', True, 'itk::Vector< float,4 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageCVF44', True, 'itk::CovariantVector< float,4 >, 4'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageD2', True, 'double, 2'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageD3', True, 'double, 3'),
  ('CudaImage', 'itk::CudaImage', 'itkCudaImageD4', True, 'double, 4'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUC2', True, 'itk::CudaImage<unsigned char, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUL2', True, 'itk::CudaImage<unsigned long, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCISS2', True, 'itk::CudaImage<signed short, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUS2', True, 'itk::CudaImage<unsigned short, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIF2', True, 'itk::CudaImage<float, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCID2', True, 'itk::CudaImage<double, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUC3', True, 'itk::CudaImage<unsigned char, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUL3', True, 'itk::CudaImage<unsigned long, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCISS3', True, 'itk::CudaImage<signed short, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUS3', True, 'itk::CudaImage<unsigned short, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIF3', True, 'itk::CudaImage<float, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCID3', True, 'itk::CudaImage<double, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUC4', True, 'itk::CudaImage<unsigned char, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUL4', True, 'itk::CudaImage<unsigned long, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCISS4', True, 'itk::CudaImage<signed short, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIUS4', True, 'itk::CudaImage<unsigned short, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIF4', True, 'itk::CudaImage<float, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCID4', True, 'itk::CudaImage<double, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF22', True, 'itk::CudaImage<itk::Vector< float,2 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF22', True, 'itk::CudaImage<itk::CovariantVector< float,2 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF23', True, 'itk::CudaImage<itk::Vector< float,2 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF23', True, 'itk::CudaImage<itk::CovariantVector< float,2 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF24', True, 'itk::CudaImage<itk::Vector< float,2 >, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF24', True, 'itk::CudaImage<itk::CovariantVector< float,2 >, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF32', True, 'itk::CudaImage<itk::Vector< float,3 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF32', True, 'itk::CudaImage<itk::CovariantVector< float,3 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF33', True, 'itk::CudaImage<itk::Vector< float,3 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF33', True, 'itk::CudaImage<itk::CovariantVector< float,3 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF34', True, 'itk::CudaImage<itk::Vector< float,3 >, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF34', True, 'itk::CudaImage<itk::CovariantVector< float,3 >, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF42', True, 'itk::CudaImage<itk::Vector< float,4 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF42', True, 'itk::CudaImage<itk::CovariantVector< float,4 >, 2>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF43', True, 'itk::CudaImage<itk::Vector< float,4 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF43', True, 'itk::CudaImage<itk::CovariantVector< float,4 >, 3>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCIVF44', True, 'itk::CudaImage<itk::Vector< float,4 >, 4>'),
  ('CudaImageDataManager', 'itk::CudaImageDataManager', 'itkCudaImageDataManagerCICVF44', True, 'itk::CudaImage<itk::CovariantVector< float,4 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUC2', True, 'itk::Image<unsigned char, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUL2', True, 'itk::Image<unsigned long, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterSS2', True, 'itk::Image<signed short, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUS2', True, 'itk::Image<unsigned short, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterF2', True, 'itk::Image<float, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterD2', True, 'itk::Image<double, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUC3', True, 'itk::Image<unsigned char, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUL3', True, 'itk::Image<unsigned long, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterSS3', True, 'itk::Image<signed short, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUS3', True, 'itk::Image<unsigned short, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterF3', True, 'itk::Image<float, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterD3', True, 'itk::Image<double, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUC4', True, 'itk::Image<unsigned char, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUL4', True, 'itk::Image<unsigned long, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterSS4', True, 'itk::Image<signed short, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterUS4', True, 'itk::Image<unsigned short, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterF4', True, 'itk::Image<float, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterD4', True, 'itk::Image<double, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF22', True, 'itk::Image<itk::Vector< float,2 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF22', True, 'itk::Image<itk::CovariantVector< float,2 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF23', True, 'itk::Image<itk::Vector< float,2 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF23', True, 'itk::Image<itk::CovariantVector< float,2 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF24', True, 'itk::Image<itk::Vector< float,2 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF24', True, 'itk::Image<itk::CovariantVector< float,2 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF32', True, 'itk::Image<itk::Vector< float,3 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF32', True, 'itk::Image<itk::CovariantVector< float,3 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF33', True, 'itk::Image<itk::Vector< float,3 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF33', True, 'itk::Image<itk::CovariantVector< float,3 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF34', True, 'itk::Image<itk::Vector< float,3 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF34', True, 'itk::Image<itk::CovariantVector< float,3 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF42', True, 'itk::Image<itk::Vector< float,4 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF42', True, 'itk::Image<itk::CovariantVector< float,4 >, 2>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF43', True, 'itk::Image<itk::Vector< float,4 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF43', True, 'itk::Image<itk::CovariantVector< float,4 >, 3>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterVF44', True, 'itk::Image<itk::Vector< float,4 >, 4>'),
  ('CudaImageFromImageFilter', 'itk::CudaImageFromImageFilter', 'itkCudaImageFromImageFilterCVF44', True, 'itk::Image<itk::CovariantVector< float,4 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUC2', False, 'itk::CudaImage<unsigned char, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUL2', False, 'itk::CudaImage<unsigned long, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCISS2', False, 'itk::CudaImage<signed short, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUS2', False, 'itk::CudaImage<unsigned short, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIF2', False, 'itk::CudaImage<float, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCID2', False, 'itk::CudaImage<double, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUC3', False, 'itk::CudaImage<unsigned char, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUL3', False, 'itk::CudaImage<unsigned long, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCISS3', False, 'itk::CudaImage<signed short, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUS3', False, 'itk::CudaImage<unsigned short, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIF3', False, 'itk::CudaImage<float, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCID3', False, 'itk::CudaImage<double, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUC4', False, 'itk::CudaImage<unsigned char, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUL4', False, 'itk::CudaImage<unsigned long, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCISS4', False, 'itk::CudaImage<signed short, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIUS4', False, 'itk::CudaImage<unsigned short, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIF4', False, 'itk::CudaImage<float, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCID4', False, 'itk::CudaImage<double, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF22', False, 'itk::CudaImage<itk::Vector< float,2 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF22', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF23', False, 'itk::CudaImage<itk::Vector< float,2 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF23', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF24', False, 'itk::CudaImage<itk::Vector< float,2 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF24', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF32', False, 'itk::CudaImage<itk::Vector< float,3 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF32', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF33', False, 'itk::CudaImage<itk::Vector< float,3 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF33', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF34', False, 'itk::CudaImage<itk::Vector< float,3 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF34', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF42', False, 'itk::CudaImage<itk::Vector< float,4 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF42', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 2>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF43', False, 'itk::CudaImage<itk::Vector< float,4 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF43', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 3>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCIVF44', False, 'itk::CudaImage<itk::Vector< float,4 >, 4>'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceCICVF44', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUC2CIUC2', False, 'itk::CudaImage<unsigned char, 2>, itk::CudaImage<unsigned char, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUC2CIUC2', False, 'itk::Image<unsigned char, 2>, itk::CudaImage<unsigned char, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUL2CIUL2', False, 'itk::CudaImage<unsigned long, 2>, itk::CudaImage<unsigned long, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUL2CIUL2', False, 'itk::Image<unsigned long, 2>, itk::CudaImage<unsigned long, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCISS2CISS2', False, 'itk::CudaImage<signed short, 2>, itk::CudaImage<signed short, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterISS2CISS2', False, 'itk::Image<signed short, 2>, itk::CudaImage<signed short, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUS2CIUS2', False, 'itk::CudaImage<unsigned short, 2>, itk::CudaImage<unsigned short, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUS2CIUS2', False, 'itk::Image<unsigned short, 2>, itk::CudaImage<unsigned short, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIF2CIF2', False, 'itk::CudaImage<float, 2>, itk::CudaImage<float, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIF2CIF2', False, 'itk::Image<float, 2>, itk::CudaImage<float, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCID2CID2', False, 'itk::CudaImage<double, 2>, itk::CudaImage<double, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterID2CID2', False, 'itk::Image<double, 2>, itk::CudaImage<double, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUC3CIUC3', False, 'itk::CudaImage<unsigned char, 3>, itk::CudaImage<unsigned char, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUC3CIUC3', False, 'itk::Image<unsigned char, 3>, itk::CudaImage<unsigned char, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUL3CIUL3', False, 'itk::CudaImage<unsigned long, 3>, itk::CudaImage<unsigned long, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUL3CIUL3', False, 'itk::Image<unsigned long, 3>, itk::CudaImage<unsigned long, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCISS3CISS3', False, 'itk::CudaImage<signed short, 3>, itk::CudaImage<signed short, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterISS3CISS3', False, 'itk::Image<signed short, 3>, itk::CudaImage<signed short, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUS3CIUS3', False, 'itk::CudaImage<unsigned short, 3>, itk::CudaImage<unsigned short, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUS3CIUS3', False, 'itk::Image<unsigned short, 3>, itk::CudaImage<unsigned short, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIF3CIF3', False, 'itk::CudaImage<float, 3>, itk::CudaImage<float, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIF3CIF3', False, 'itk::Image<float, 3>, itk::CudaImage<float, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCID3CID3', False, 'itk::CudaImage<double, 3>, itk::CudaImage<double, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterID3CID3', False, 'itk::Image<double, 3>, itk::CudaImage<double, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUC4CIUC4', False, 'itk::CudaImage<unsigned char, 4>, itk::CudaImage<unsigned char, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUC4CIUC4', False, 'itk::Image<unsigned char, 4>, itk::CudaImage<unsigned char, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUL4CIUL4', False, 'itk::CudaImage<unsigned long, 4>, itk::CudaImage<unsigned long, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUL4CIUL4', False, 'itk::Image<unsigned long, 4>, itk::CudaImage<unsigned long, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCISS4CISS4', False, 'itk::CudaImage<signed short, 4>, itk::CudaImage<signed short, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterISS4CISS4', False, 'itk::Image<signed short, 4>, itk::CudaImage<signed short, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIUS4CIUS4', False, 'itk::CudaImage<unsigned short, 4>, itk::CudaImage<unsigned short, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUS4CIUS4', False, 'itk::Image<unsigned short, 4>, itk::CudaImage<unsigned short, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIF4CIF4', False, 'itk::CudaImage<float, 4>, itk::CudaImage<float, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIF4CIF4', False, 'itk::Image<float, 4>, itk::CudaImage<float, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCID4CID4', False, 'itk::CudaImage<double, 4>, itk::CudaImage<double, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterID4CID4', False, 'itk::Image<double, 4>, itk::CudaImage<double, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF22CIVF22', False, 'itk::CudaImage<itk::Vector< float,2 >, 2>, itk::CudaImage<itk::Vector< float,2 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF22CIVF22', False, 'itk::Image<itk::Vector< float,2 >, 2>, itk::CudaImage<itk::Vector< float,2 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF22CICVF22', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 2>, itk::CudaImage<itk::CovariantVector< float,2 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF22CICVF22', False, 'itk::Image<itk::CovariantVector< float,2 >, 2>, itk::CudaImage<itk::CovariantVector< float,2 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF23CIVF23', False, 'itk::CudaImage<itk::Vector< float,2 >, 3>, itk::CudaImage<itk::Vector< float,2 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF23CIVF23', False, 'itk::Image<itk::Vector< float,2 >, 3>, itk::CudaImage<itk::Vector< float,2 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF23CICVF23', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 3>, itk::CudaImage<itk::CovariantVector< float,2 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF23CICVF23', False, 'itk::Image<itk::CovariantVector< float,2 >, 3>, itk::CudaImage<itk::CovariantVector< float,2 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF24CIVF24', False, 'itk::CudaImage<itk::Vector< float,2 >, 4>, itk::CudaImage<itk::Vector< float,2 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF24CIVF24', False, 'itk::Image<itk::Vector< float,2 >, 4>, itk::CudaImage<itk::Vector< float,2 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF24CICVF24', False, 'itk::CudaImage<itk::CovariantVector< float,2 >, 4>, itk::CudaImage<itk::CovariantVector< float,2 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF24CICVF24', False, 'itk::Image<itk::CovariantVector< float,2 >, 4>, itk::CudaImage<itk::CovariantVector< float,2 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF32CIVF32', False, 'itk::CudaImage<itk::Vector< float,3 >, 2>, itk::CudaImage<itk::Vector< float,3 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF32CIVF32', False, 'itk::Image<itk::Vector< float,3 >, 2>, itk::CudaImage<itk::Vector< float,3 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF32CICVF32', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 2>, itk::CudaImage<itk::CovariantVector< float,3 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF32CICVF32', False, 'itk::Image<itk::CovariantVector< float,3 >, 2>, itk::CudaImage<itk::CovariantVector< float,3 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF33CIVF33', False, 'itk::CudaImage<itk::Vector< float,3 >, 3>, itk::CudaImage<itk::Vector< float,3 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF33CIVF33', False, 'itk::Image<itk::Vector< float,3 >, 3>, itk::CudaImage<itk::Vector< float,3 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF33CICVF33', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 3>, itk::CudaImage<itk::CovariantVector< float,3 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF33CICVF33', False, 'itk::Image<itk::CovariantVector< float,3 >, 3>, itk::CudaImage<itk::CovariantVector< float,3 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF34CIVF34', False, 'itk::CudaImage<itk::Vector< float,3 >, 4>, itk::CudaImage<itk::Vector< float,3 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF34CIVF34', False, 'itk::Image<itk::Vector< float,3 >, 4>, itk::CudaImage<itk::Vector< float,3 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF34CICVF34', False, 'itk::CudaImage<itk::CovariantVector< float,3 >, 4>, itk::CudaImage<itk::CovariantVector< float,3 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF34CICVF34', False, 'itk::Image<itk::CovariantVector< float,3 >, 4>, itk::CudaImage<itk::CovariantVector< float,3 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF42CIVF42', False, 'itk::CudaImage<itk::Vector< float,4 >, 2>, itk::CudaImage<itk::Vector< float,4 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF42CIVF42', False, 'itk::Image<itk::Vector< float,4 >, 2>, itk::CudaImage<itk::Vector< float,4 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF42CICVF42', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 2>, itk::CudaImage<itk::CovariantVector< float,4 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF42CICVF42', False, 'itk::Image<itk::CovariantVector< float,4 >, 2>, itk::CudaImage<itk::CovariantVector< float,4 >, 2>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF43CIVF43', False, 'itk::CudaImage<itk::Vector< float,4 >, 3>, itk::CudaImage<itk::Vector< float,4 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF43CIVF43', False, 'itk::Image<itk::Vector< float,4 >, 3>, itk::CudaImage<itk::Vector< float,4 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF43CICVF43', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 3>, itk::CudaImage<itk::CovariantVector< float,4 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF43CICVF43', False, 'itk::Image<itk::CovariantVector< float,4 >, 3>, itk::CudaImage<itk::CovariantVector< float,4 >, 3>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCIVF44CIVF44', False, 'itk::CudaImage<itk::Vector< float,4 >, 4>, itk::CudaImage<itk::Vector< float,4 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIVF44CIVF44', False, 'itk::Image<itk::Vector< float,4 >, 4>, itk::CudaImage<itk::Vector< float,4 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterCICVF44CICVF44', False, 'itk::CudaImage<itk::CovariantVector< float,4 >, 4>, itk::CudaImage<itk::CovariantVector< float,4 >, 4>'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterICVF44CICVF44', False, 'itk::Image<itk::CovariantVector< float,4 >, 4>, itk::CudaImage<itk::CovariantVector< float,4 >, 4>'),
)
factories = ()
