# coding: utf-8

"""
    Mycelium Worker (Client) API

    Configuration API for Mycelium client workers

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mycelium.api.generated_sources.worker_schemas.models.worker_client_api_section import WorkerClientAPISection  # noqa: E501

class TestWorkerClientAPISection(unittest.TestCase):
    """WorkerClientAPISection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkerClientAPISection:
        """Test WorkerClientAPISection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkerClientAPISection`
        """
        model = WorkerClientAPISection()  # noqa: E501
        if include_optional:
            return WorkerClientAPISection(
                host = '',
                port = 56
            )
        else:
            return WorkerClientAPISection(
                host = '',
                port = 56,
        )
        """

    def testWorkerClientAPISection(self):
        """Test WorkerClientAPISection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
