
from typing import Generic, List, TypeVar, Type, Optional, Any, Protocol
from .base import Page, PageRequest

T = TypeVar("T")

class CrudRepository(Protocol, Generic[T]):
    model: Type[T]
    def getAll(self, limit: Optional[int]) -> List[T]: ...
    def get(self, id_: Any) -> T: ...
    def try_get(self, id_: Any) -> Optional[T]: ...
    def add(self, entity: T) -> T: ...
    def update(self, entity: T) -> T: ...
    def remove(self, entity: T) -> None: ...
    def delete_by_id(self, id_: Any) -> bool: ...
    def page(self, page: PageRequest, spec=None, order_by=None) -> Page[T]: ...
