"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class RbacResource(str, Enum):
    GROUPS = "groups"
    DATASETS = "datasets"
    DATASET_PROVIDERS = "dataset-providers"
    PROJECTS = "projects"
    DASHBOARDS = "dashboards"
    MACROS = "macros"
    NOTEBOOKS = "notebooks"
