"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rbacresource import RbacResource
from cribl_control_plane.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ResourcePolicyTypedDict(TypedDict):
    gid: str
    policy: str
    type: RbacResource
    id: NotRequired[str]


class ResourcePolicy(BaseModel):
    gid: str

    policy: str

    type: RbacResource

    id: Optional[str] = None
