# Generated by Django 3.2.11 on 2022-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0011_auto_20220203_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpingrecord',
            name='last_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
