# Generated by Django 4.0.2 on 2022-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0012_fuelpingrecord_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordwebhook',
            name='no_at_pings',
            field=models.BooleanField(default=False),
        ),
    ]
