# Generated by Django 5.2.7 on 2025-10-11 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_visitor_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
