# coding: utf-8

PRODUCT_KINDER_ENVIRONMENT = (
    'KINDER_CONFIG_PATH')
PRODUCT_WEB_EDU_ENVIRONMENT = (
    'WEB_EDU_CONFIG_PATH')
PRODUCT_SSUZ_ENVIRONMENT = (
    'SSUZ_CONFIG_PATH')
PRODUCT_EDUADNL_ENVIRONMENT = (
    'EXTEDU_CONFIG_PATH'
)
PRODUCT_GENIUS_ENVIRONMENT = 'GENIUS_CONFIG_PATH'

PRODUCT_KINDER = (
    'kinder')
PRODUCT_WEB_EDU = (
    'web_edu')
PRODUCT_SSUZ = (
    'ssuz')
PRODUCT_EDUADNL = (
    'eduadnl')
PRODUCT_GENIUS = 'genius'

PRODUCTS = {
    PRODUCT_KINDER_ENVIRONMENT: PRODUCT_KINDER,
    PRODUCT_WEB_EDU_ENVIRONMENT: PRODUCT_WEB_EDU,
    PRODUCT_SSUZ_ENVIRONMENT: PRODUCT_SSUZ,
    PRODUCT_EDUADNL_ENVIRONMENT: PRODUCT_EDUADNL,
    PRODUCT_GENIUS_ENVIRONMENT: PRODUCT_GENIUS,
}
