import polars as pl
from .database import Database as Database
from _typeshed import Incomplete
from datahub.setting import PostgresSetting as PostgresSetting
from datahub.utils.logger import logger as logger
from datetime import date
from typing import Any, Sequence

class Postgres(Database):
    db_url: Incomplete
    def __init__(self, setting: PostgresSetting) -> None: ...
    def upsert_many(self, table_name: str, data: list[dict[str, Any]], keys: list[str]) -> int: ...
    def get_trading_days(self, start_date: date, end_date: date, market: str = 'XSHG') -> list[date]: ...
    def get_blacklist(self, blacklist_ids: Sequence[str], end_date: date = None) -> pl.DataFrame: ...
    def get_sbl_list(self, brokers: Sequence[str] = (), sbl_ids: Sequence[str] = (), start_date: date | None = None, end_date: date | None = None) -> pl.DataFrame: ...
