from pathlib import Path

MAX_HELP_CONTENT_WIDTH = 120

WORKFLOWS_DIR_NAME = "workflows"
GITHUB_WORKFLOWS_DIR = f".github/{WORKFLOWS_DIR_NAME}"

BASE_WORKFLOW_FILE_NAME = "continuous-delivery.yml"
BUILD_WORKFLOW_FILE_NAME = "build.yml"
RELEASE_WORKFLOW_FILE_NAME = "release.yml"
HELPER_SCRIPT_FILE_NAME = "verify-upstream-has-not-changed.sh"
TEST_E2E_WORKFLOW_FILE_NAME = "test-e2e.yml"

BASE_WORKFLOW_ASSET_PATH = Path(WORKFLOWS_DIR_NAME, BASE_WORKFLOW_FILE_NAME)
BUILD_WORKFLOW_ASSET_PATH = Path(WORKFLOWS_DIR_NAME, BUILD_WORKFLOW_FILE_NAME)
HELPER_SCRIPT_ASSET_PATH = Path(WORKFLOWS_DIR_NAME, HELPER_SCRIPT_FILE_NAME)
RELEASE_WORKFLOW_ASSET_PATH = Path(WORKFLOWS_DIR_NAME, RELEASE_WORKFLOW_FILE_NAME)
TEST_E2E_WORKFLOW_ASSET_PATH = Path(WORKFLOWS_DIR_NAME, TEST_E2E_WORKFLOW_FILE_NAME)

BASE_WORKFLOW_FILE_PATH = Path(GITHUB_WORKFLOWS_DIR, BASE_WORKFLOW_FILE_NAME)
BUILD_WORKFLOW_FILE_PATH = Path(GITHUB_WORKFLOWS_DIR, BUILD_WORKFLOW_FILE_NAME)
HELPER_SCRIPT_FILE_PATH = Path(GITHUB_WORKFLOWS_DIR, HELPER_SCRIPT_FILE_NAME)
RELEASE_WORKFLOW_FILE_PATH = Path(GITHUB_WORKFLOWS_DIR, RELEASE_WORKFLOW_FILE_NAME)
TEST_E2E_WORKFLOW_FILE_PATH = Path(GITHUB_WORKFLOWS_DIR, TEST_E2E_WORKFLOW_FILE_NAME)
