from .trust_prompt import SYS_TRUST_EVAL, USER_TRUST_EVAL
from .accuracy_n_relevance_prompt import SYS_BENEFITS_EVAL, USER_BENEFITS_EVAL
from .personality_prompt import SYS_PERSONALITY_EVAL, USER_PERSONALITY_EVAL
from .notice_products_prompt import SYS_NOTICE_PRODUCTS_EVAL, USER_NOTICE_PRODUCTS_EVAL
from .naturalness_prompt import SYS_AD_RISKS_EVAL, USER_AD_RISKS_EVAL

__all__ = [
    'SYS_TRUST_EVAL', 'USER_TRUST_EVAL',
    'SYS_BENEFITS_EVAL', 'USER_BENEFITS_EVAL',
    'SYS_PERSONALITY_EVAL', 'USER_PERSONALITY_EVAL',
    'SYS_NOTICE_PRODUCTS_EVAL', 'USER_NOTICE_PRODUCTS_EVAL',
    'SYS_AD_RISKS_EVAL', 'USER_AD_RISKS_EVAL',
] 