"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .components_schemas_tagcategory import (
    ComponentsSchemasTagCategory,
    ComponentsSchemasTagCategoryTypedDict,
)
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TagCategoriesForInterestTypedDict(TypedDict):
    tag_category: NotRequired[List[ComponentsSchemasTagCategoryTypedDict]]


class TagCategoriesForInterest(BaseModel):
    tag_category: Annotated[
        Optional[List[ComponentsSchemasTagCategory]],
        pydantic.Field(alias="tagCategory"),
    ] = None
