"""Type stubs for Merkle tree implementations."""

from __future__ import annotations

from typing import Any, Final, Iterator, Protocol, Union, Literal, Optional
from typing_extensions import TypeAlias, override

from collections.abc import Sequence

from mrkle.typing import BufferLike as Buffer, File
from mrkle.crypto.typing import Digest

class _MrkleTreeBase(Protocol):
    """Base protocol for Merkle tree implementations."""

    def root(self) -> bytes:
        """Return the root hash as a hex string."""
        ...
    def is_empty(self) -> bool:
        """Check if the tree is empty."""
        ...
    def capacity(self) -> int:
        """Return the capacity of the tree."""
        ...
    def __len__(self) -> int:
        """Return the number of nodes in the tree."""
        ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    def __getitem__(self, key: Union[int, slice, Sequence[int]]) -> list[Any]: ...
    def to_string(self) -> str:
        """Return a string representation of the tree structure."""
        ...
    def dumps(
        self,
        fp: Optional[File] = None,
        *,
        encoding: Literal["utf-8", "bytes"] = "utf-8",
        indent: Optional[int] = None,
    ) -> Optional[bytes]: ...
    @staticmethod
    def loads(data: Union[str, bytes], format: Literal["json"]) -> "Tree_T": ...
    @staticmethod
    def load(fp: File, format: Literal["json"]) -> "Tree_T": ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Tree_T": ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

# Blake2s
class MrkleTreeBlake2s(_MrkleTreeBase):
    """Merkle tree using Blake2s hash algorithm."""

    def leaves(self) -> list[MrkleNodeBlake2s]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeBlake2s: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterBlake2s(Iterator[Node_T]):
    """Iterator for Blake2s Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterBlake2s: ...
    @override
    def __next__(self) -> Node_T: ...

# Blake2b
class MrkleTreeBlake2b(_MrkleTreeBase):
    """Merkle tree using Blake2b hash algorithm."""

    def leaves(self) -> list[MrkleNodeBlake2b]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeBlake2b: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterBlake2b(Iterator[Node_T]):
    """Iterator for Blake2b Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterBlake2b: ...
    @override
    def __next__(self) -> Node_T: ...

# Keccak224
class MrkleTreeKeccak224(_MrkleTreeBase):
    """Merkle tree using Keccak224 hash algorithm."""

    def leaves(self) -> list[MrkleNodeKeccak224]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeKeccak224: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterKeccak224(Iterator[Node_T]):
    """Iterator for Keccak224 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterKeccak224: ...
    @override
    def __next__(self) -> Node_T: ...

# Keccak256
class MrkleTreeKeccak256(_MrkleTreeBase):
    """Merkle tree using Keccak256 hash algorithm."""

    def leaves(self) -> list[MrkleNodeKeccak256]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeKeccak256: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterKeccak256(Iterator[Node_T]):
    """Iterator for Keccak256 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterKeccak256: ...
    @override
    def __next__(self) -> Node_T: ...

# Keccak384
class MrkleTreeKeccak384(_MrkleTreeBase):
    """Merkle tree using Keccak384 hash algorithm."""

    def leaves(self) -> list[MrkleNodeKeccak384]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeKeccak384: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterKeccak384(Iterator[Node_T]):
    """Iterator for Keccak384 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterKeccak384: ...
    @override
    def __next__(self) -> Node_T: ...

# Keccak512
class MrkleTreeKeccak512(_MrkleTreeBase):
    """Merkle tree using Keccak512 hash algorithm."""

    def leaves(self) -> list[MrkleNodeKeccak512]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeKeccak512: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterKeccak512(Iterator[Node_T]):
    """Iterator for Keccak512 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterKeccak512: ...
    @override
    def __next__(self) -> Node_T: ...

# SHA1
class MrkleTreeSha1(_MrkleTreeBase):
    """Merkle tree using SHA1 hash algorithm."""

    def leaves(self) -> list[MrkleNodeSha1]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeSha1: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterSha1(Iterator[Node_T]):
    """Iterator for SHA1 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterSha1: ...
    @override
    def __next__(self) -> Node_T: ...

# SHA224
class MrkleTreeSha224(_MrkleTreeBase):
    """Merkle tree using SHA224 hash algorithm."""

    def leaves(self) -> list[MrkleNodeSha224]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeSha224: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterSha224(Iterator[Node_T]):
    """Iterator for SHA224 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterSha224: ...
    @override
    def __next__(self) -> Node_T: ...

# SHA256
class MrkleTreeSha256(_MrkleTreeBase):
    """Merkle tree using SHA256 hash algorithm."""

    def leaves(self) -> list[MrkleNodeSha256]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeSha256: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterSha256(Iterator[Node_T]):
    """Iterator for SHA256 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterSha256: ...
    @override
    def __next__(self) -> Node_T: ...

# SHA384
class MrkleTreeSha384(_MrkleTreeBase):
    """Merkle tree using SHA384 hash algorithm."""

    def leaves(self) -> list[MrkleNodeSha384]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeSha384: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterSha384(Iterator[Node_T]):
    """Iterator for SHA384 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterSha384: ...
    @override
    def __next__(self) -> Node_T: ...

# SHA512
class MrkleTreeSha512(_MrkleTreeBase):
    """Merkle tree using SHA512 hash algorithm."""

    def leaves(self) -> list[MrkleNodeSha512]: ...
    @staticmethod
    def dtype() -> Digest: ...
    @classmethod
    def from_leaves(
        cls, leaves: Union[Sequence[Union[Buffer, str]], Iterator[Union[Buffer, str]]]
    ) -> MrkleTreeSha512: ...
    def __iter__(self) -> Iterable_T: ...

class MrkleTreeIterSha512(Iterator[Node_T]):
    """Iterator for SHA512 Merkle tree."""

    @override
    def __iter__(self) -> MrkleTreeIterSha512: ...
    @override
    def __next__(self) -> Node_T: ...

class MrkleNodeBlake2s:
    """Merkle tree node using Blake2s hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeBlake2b:
    """Merkle tree node using Blake2b hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeKeccak224:
    """Merkle tree node using Keccak224 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeKeccak256:
    """Merkle tree node using Keccak256 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeKeccak384:
    """Merkle tree node using Keccak384 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeKeccak512:
    """Merkle tree node using Keccak512 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeSha1:
    """Merkle tree node using SHA1 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeSha224:
    """Merkle tree node using SHA224 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeSha256:
    """Merkle tree node using SHA256 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeSha384:
    """Merkle tree node using SHA384 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class MrkleNodeSha512:
    """Merkle tree node using SHA512 hash algorithm."""

    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def parent(self) -> Optional[int]: ...
    def children(self) -> Sequence[int]: ...
    @staticmethod
    def leaf(payload: bytes) -> MrkleNodeBlake2s: ...
    @staticmethod
    def leaf_with_digest(payload: bytes, hash: bytes) -> Node_T: ...
    @staticmethod
    def dtype() -> Digest: ...
    def value(self) -> Optional[bytes]: ...
    def is_leaf(self) -> bool: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

Node_T: TypeAlias = Union[
    MrkleNodeBlake2s,
    MrkleNodeBlake2b,
    MrkleNodeKeccak224,
    MrkleNodeKeccak256,
    MrkleNodeKeccak384,
    MrkleNodeKeccak512,
    MrkleNodeSha1,
    MrkleNodeSha224,
    MrkleNodeSha256,
    MrkleNodeSha384,
    MrkleNodeSha512,
]

Tree_T: TypeAlias = Union[
    MrkleTreeBlake2s,
    MrkleTreeBlake2b,
    MrkleTreeKeccak224,
    MrkleTreeKeccak256,
    MrkleTreeKeccak384,
    MrkleTreeKeccak512,
    MrkleTreeSha1,
    MrkleTreeSha224,
    MrkleTreeSha256,
    MrkleTreeSha384,
    MrkleTreeSha512,
]

Iterable_T: TypeAlias = Union[
    MrkleTreeIterBlake2s,
    MrkleTreeIterBlake2b,
    MrkleTreeIterKeccak224,
    MrkleTreeIterKeccak256,
    MrkleTreeIterKeccak384,
    MrkleTreeIterKeccak512,
    MrkleTreeIterSha1,
    MrkleTreeIterSha224,
    MrkleTreeIterSha256,
    MrkleTreeIterSha384,
    MrkleTreeIterSha512,
]

TREE_MAP: Final[dict[str, Tree_T]]
NODE_MAP: Final[dict[str, Node_T]]
