"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CasebaseSearchSettingsTypedDict(TypedDict):
    close_session_on_accept: NotRequired[bool]
    r"""indicates whether to close the Guided Help session upon acceptance of answer"""
    close_session_on_reject: NotRequired[bool]
    r"""indicates wheather to reject the Guided Helo session upon rejection of answer"""


class CasebaseSearchSettings(BaseModel):
    close_session_on_accept: Annotated[
        Optional[bool], pydantic.Field(alias="closeSessionOnAccept")
    ] = None
    r"""indicates whether to close the Guided Help session upon acceptance of answer"""

    close_session_on_reject: Annotated[
        Optional[bool], pydantic.Field(alias="closeSessionOnReject")
    ] = None
    r"""indicates wheather to reject the Guided Helo session upon rejection of answer"""
