# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0004_auto_20190227_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hauteskundeemaitzaktokian',
            options={'ordering': ('hauteskundeatokian', '-botoak', 'alderdia'), 'verbose_name': 'Emaitza', 'verbose_name_plural': 'Emaitzak'},
        ),
        migrations.RenameField(
            model_name='hauteskundeemaitzaktokian',
            old_name='hauteskundea',
            new_name='hauteskundeatokian',
        ),
    ]
