# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0005_auto_20190227_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauteskundea',
            name='izen_motza',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
