# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0007_auto_20190227_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauteskundea',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tktokia',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
