# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 15:33
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0015_auto_20190310_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauteskundemota',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alderdia',
            name='kolorea',
            field=colorfield.fields.ColorField(default=b'#000000', max_length=18),
        ),
    ]
