# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0016_auto_20190311_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='HauteskundeOharrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oharrak', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('alderdia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tk_hauteskundeak.Alderdia')),
                ('hauteskundea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tk_hauteskundeak.Hauteskundea')),
            ],
            options={
                'verbose_name': 'Hauteskunde Oharra',
                'verbose_name_plural': 'Hauteskunde Oharrak',
            },
        ),
    ]
