# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0018_auto_20190321_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauteskundemota',
            name='order',
            field=models.IntegerField(default=0, help_text=b'Ordenatzeko erabiliko dugu'),
        ),
    ]
