# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0025_auto_20190325_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tkalderdia',
            name='logoa',
        ),
        migrations.RemoveField(
            model_name='tokia',
            name='tktokia',
        ),
        migrations.AddField(
            model_name='tokia',
            name='aita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tk_hauteskundeak.Tokia'),
        ),
        migrations.AddField(
            model_name='tokia',
            name='boundary_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokia',
            name='is_default',
            field=models.BooleanField(default=False, help_text=b'Herri edo eskualde nagusia. Bakarra aukeratu.'),
        ),
        migrations.AddField(
            model_name='tokia',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokia',
            name='mota',
            field=models.IntegerField(choices=[(0, b'Mahaia'), (1, b'Herria'), (2, b'Eskualdea'), (3, b'Kuadrila'), (4, b'Herrialdea')], default=1),
        ),
        migrations.AddField(
            model_name='tokia',
            name='slug',
            field=models.SlugField(default='kk'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TkAlderdia',
        ),
    ]
