# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0029_auto_20190404_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauteskundeatokian',
            name='alderdien_botoak',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='hauteskundeemaitzaktokian',
            name='ehunekoa',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
