# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tk_hauteskundeak', '0035_auto_20190407_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hauteskundeacachemota',
            old_name='hauteskundemoa',
            new_name='mota',
        ),
    ]
