# Generated by Django 4.1.6 on 2023-05-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tk_hauteskundeak", "0050_apiresourceconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiresourceconfig",
            options={
                "verbose_name": "API konexioa",
                "verbose_name_plural": "API konexioak",
            },
        ),
        migrations.AddField(
            model_name="apiresourceconfig",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Aktibatuta"),
        ),
        migrations.AddField(
            model_name="apiresourceconfig",
            name="protocol_charset",
            field=models.CharField(
                choices=[("latin-1", "ISO-8859-1"), ("utf-8", "UTF-8")],
                default="utf-8",
                max_length=8,
                verbose_name="Protokolo kodetzea",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="charset",
            field=models.CharField(
                choices=[("latin-1", "ISO-8859-1"), ("utf-8", "UTF-8")],
                max_length=8,
                verbose_name="Kodetzea",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="domain",
            field=models.CharField(max_length=100, verbose_name="Domainua"),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="filename",
            field=models.CharField(max_length=100, verbose_name="Fitxategia"),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="format",
            field=models.CharField(
                choices=[("TXT", "TXT"), ("XML", "XML"), ("CSV", "CSV")],
                max_length=5,
                verbose_name="Formatua",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="foru_aldundia",
            field=models.CharField(
                choices=[
                    ("ara", "Araba"),
                    ("biz", "Bizkaia"),
                    ("gip", "Gipuzkoa"),
                    ("naf", "Nafarroa"),
                ],
                max_length=3,
                null=True,
                verbose_name="Foru aldundia",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="hauteskundea",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hauteskundea",
                to="tk_hauteskundeak.hauteskundea",
                verbose_name="Hauteskundea",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="passwd",
            field=models.CharField(max_length=100, null=True, verbose_name="Pasahitza"),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="path",
            field=models.CharField(max_length=255, verbose_name="Direktorioa"),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="protocol",
            field=models.CharField(
                choices=[("HTTPS", "HTTPS"), ("FTP", "FTP")],
                max_length=6,
                verbose_name="Protokoloa",
            ),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="username",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Erabiltzailea"
            ),
        ),
    ]
