# Generated by Django 4.1.6 on 2023-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tk_hauteskundeak", "0056_alter_alderdia_bn_araba_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiresourceconfig",
            name="last_parsed",
            field=models.DateTimeField(null=True),
        ),
    ]
