# Generated by Django 4.1.6 on 2023-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tk_hauteskundeak", "0058_remove_alderdia_bn_araba_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hauteskundea",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="Herrietako portadetako estatistikak ezkutatzen ditu. Hauteskundea amaitu ostean markatu.",
                verbose_name="Itxita",
            ),
        ),
    ]
