# Generated by Django 4.1.6 on 2023-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tk_hauteskundeak", "0059_alter_hauteskundea_is_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alderdia",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="apiresourceconfig",
            name="data_set",
            field=models.CharField(
                choices=[
                    ("ara", "Araba"),
                    ("biz", "Bizkaia"),
                    ("gip", "Gipuzkoa"),
                    ("naf", "Nafarroa"),
                    ("uda", "Ministerioa (Udalak)"),
                    ("kon", "Ministerioa (Kongresua)"),
                ],
                help_text="Adierazi datuen iturria",
                max_length=3,
                null=True,
                verbose_name="Datuen iturria",
            ),
        ),
    ]
