# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weaveapi/synthesize/v1/inline_data.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    "",
    "weaveapi/synthesize/v1/inline_data.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(weaveapi/synthesize/v1/inline_data.proto\x12\x16weaveapi.synthesize.v1"d\n\nInlineData\x12:\n\x06\x66ormat\x18\x01 \x01(\x0e\x32".weaveapi.synthesize.v1.DataFormatR\x06\x66ormat\x12\x1a\n\x08\x63ontents\x18\x02 \x01(\x0cR\x08\x63ontents*\x98\x01\n\nDataFormat\x12\x1b\n\x17\x44\x41TA_FORMAT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44\x41TA_FORMAT_CSV\x10\x01\x12\x14\n\x10\x44\x41TA_FORMAT_JSON\x10\x02\x12\x17\n\x13\x44\x41TA_FORMAT_PARQUET\x10\x03\x12\x14\n\x10\x44\x41TA_FORMAT_AVRO\x10\x04\x12\x13\n\x0f\x44\x41TA_FORMAT_ORC\x10\x05\x42\xe9\x01\n\x1a\x63om.weaveapi.synthesize.v1B\x0fInlineDataProtoP\x01Z@github.com/weave-labs/weave-go/weaveapi/synthesize/v1;synthesize\xa2\x02\x03WSX\xaa\x02\x16Weaveapi.Synthesize.V1\xca\x02\x16Weaveapi\\Synthesize\\V1\xe2\x02"Weaveapi\\Synthesize\\V1\\GPBMetadata\xea\x02\x18Weaveapi::Synthesize::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "weaveapi.synthesize.v1.inline_data_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b'\n\032com.weaveapi.synthesize.v1B\017InlineDataProtoP\001Z@github.com/weave-labs/weave-go/weaveapi/synthesize/v1;synthesize\242\002\003WSX\252\002\026Weaveapi.Synthesize.V1\312\002\026Weaveapi\\Synthesize\\V1\342\002"Weaveapi\\Synthesize\\V1\\GPBMetadata\352\002\030Weaveapi::Synthesize::V1'
    _globals["_DATAFORMAT"]._serialized_start = 171
    _globals["_DATAFORMAT"]._serialized_end = 323
    _globals["_INLINEDATA"]._serialized_start = 68
    _globals["_INLINEDATA"]._serialized_end = 168
# @@protoc_insertion_point(module_scope)
