companies = {
  "Petrobras": ["PETR3", "PETR4"],
  "Vale": ["VALE3"],
  "Itaú Unibanco": ["ITUB3", "ITUB4"],
  "Bradesco": ["BBDC3", "BBDC4"],
  "Banco do Brasil": ["BBAS3"],
  "Santander Brasil": ["SANB11"],
  "BTG Pactual": ["BPAC11"],
  "Ambev": ["ABEV3"],
  "Weg": ["WEGE3"],
  "JBS": ["JBSS3"],
  "Gerdau": ["GGBR3", "GGBR4"],
  "Usiminas": ["USIM5"],
  "CSN": ["CSNA3"],
  "Cosan": ["CSAN3"],
  "Ultrapar": ["UGPA3"],
  "Raia Drogasil": ["RADL3"],
  "Fleury": ["FLRY3"],
  "Rede D'Or": ["RDOR3"],
  "Hapvida": ["HAPV3"],
  "Sul América": ["SULA11"],
  "Magazine Luiza": ["MGLU3"],
  "Via": ["VIIA3"],
  "Lojas Renner": ["LREN3"],
  "GPA": ["PCAR3"],
  "Assaí": ["ASAI3"],
  "Localiza": ["RENT3"],
  "Movida": ["MOVI3"],
  "3R Petroleum": ["RRRP3"],
  "PetroRio": ["PRIO3"],
  "Eletrobras": ["ELET3", "ELET6"],
  "Engie Brasil": ["EGIE3"],
  "Equatorial Energia": ["EQTL3"],
  "Cemig": ["CMIG4"],
  "Copel": ["CPLE6"],
  "AES Brasil": ["AESB3"],
  "Sabesp": ["SBSP3"],
  "Telefônica Brasil": ["VIVT3"],
  "TIM": ["TIMS3"],
  "Oi": ["OIBR3"],
  "Embraer": ["EMBR3"],
  "Azul": ["AZUL4"],
  "Gol": ["GOLL4"],
  "Rumo": ["RAIL3"],
  "CCR": ["CCRO3"],
  "Ecovias": ["ECOR3"],
  "Suzano": ["SUZB3"],
  "Klabin": ["KLBN11"],
  "Fibria": ["FIBR3"],
  "Braskem": ["BRKM5"],
  "Marcopolo": ["POMO4"],
  "Hypermarcas": ["HYPE3"],
  "Natura": ["NTCO3"],
  "Multiplan": ["MULT3"],
  "IGB Eletrônico": ["IGTI11"],
  "B3": ["B3SA3"],
  "IRB Brasil": ["IRBR3"],
  "CVC Brasil": ["CVCB3"],
  "YDUQS": ["YDUQ3"],
  "Anima": ["ANIM3"],
  "Totvs": ["TOTS3"],
  "Locaweb": ["LWSA3"],
  "Méliuz": ["CASH3"],
  "Banco Inter": ["BIDI11"],
  "PagSeguro": ["PAGS34"],
  "Stone": ["STOC31"],
  "XP Inc": ["XPBR31"],
  "Nu Holdings": ["NUBR33"],
  "Oi": ["OIBR3"],
  "Light": ["LIGT3"],
  "Alpargatas": ["ALPA4"],
  "C&A": ["CEAB3"],
  "Grendene": ["GRND3"],
  "Vulcabrás": ["VULC3"],
  "Minerva": ["BEEF3"],
  "Marfrig": ["MRFG3"],
  "BRF": ["BRFS3"],
  "M. Dias Branco": ["MDIA3"],
  "Camil": ["CAML3"],
  "SLC Agrícola": ["SLCE3"],
  "BrasilAgro": ["AGRO3"],
  "Tereos": ["TESA3"],
  "Tupy": ["TUPY3"],
  "Wiz": ["WIZS3"],
  "Porto Seguro": ["PSSA3"],
  "BB Seguridade": ["BBSE3"],
  "Cielo": ["CIEL3"],
  "Totvs": ["TOTS3"],
  "Linx": ["LINX3"],
  "TOTVS": ["TOTS3"],
  "Qualicorp": ["QUAL3"],
  "Hcor": ["HCOR3"],
  "Dasa": ["DASA3"],
  "Alliar": ["AALR3"],
  "Odontoprev": ["ODPV3"],
  "NotreDame": ["GNDI3"],
  "Cogna": ["COGN3"],
  "Estácio": ["YDUQ3"],
  "Ser Educacional": ["SEER3"],
  "Águas do Brasil": ["AALR3"],
  "SABESP": ["SBSP3"],
  "Sanepar": ["SAPR11"],
  "Transmissão Paulista": ["TRPL4"],
  "Taesa": ["TAEE11"],
  "Omega Energia": ["MEGA3"],
  "Auren": ["AURE3"],
  "Celesc": ["CLSC4"],
  "Eneva": ["ENEV3"],
  "Tronox": ["TXRX3"],
  "Unipar": ["UNIP6"],
  "Iochpe-Maxion": ["MYPK3"],
  "Randon": ["RAPT4"],
  "Tupy": ["TUPY3"],
  "Taurus": ["TASA4"],
  "Simpar": ["SIMH3"],
  "JHSF": ["JHSF3"],
  "Cyrela": ["CYRE3"],
  "MRV": ["MRVE3"],
  "Eztec": ["EZTC3"],
  "Even": ["EVEN3"],
  "Helbor": ["HBOR3"],
  "Direcional": ["DIRR3"],
  "Tegra": ["TGRA3"],
  "Plano & Plano": ["PLPL3"],
  "Viver": ["VIVR3"],
  "Alupar": ["ALUP11"],
  "AES Brasil": ["AESB3"],
  "CPFL Energia": ["CPFE3"],
  "Neoenergia": ["NEOE3"],
  "EDP Brasil": ["ENBR3"],
  "Tronox": ["TXRX3"],
  "Unipar": ["UNIP6"],
  "Ferbasa": ["FESA4"],
  "Mangels": ["MGEL4"],
  "Metalúrgica Gerdau": ["GOAU4"],
  "Siderúrgica Nacional": ["CSNA3"],
  "Vibra": ["VBBR3"],
  "Ultragaz": ["UGPA3"],
  "PetroRecôncavo": ["RECV3"],
  "Enauta": ["ENAT3"],
  "Priner": ["PRNR3"],
  "Vittia": ["VITT3"],
  "Ouro Verde": ["ORVR3"],
  "Boa Vista": ["BOAS3"],
  "Getnet": ["GETT11"],
  "ClearSale": ["CLSA3"],
  "Armac": ["ARML3"],
  "Brisanet": ["BRIT3"],
  "Lupatech": ["LUPA3"],
  "Paranapanema": ["PMAM3"],
  "Tecnisa": ["TCSA3"],
  "Trisul": ["TRIS3"],
  "Vittia": ["VITT3"],
  "Nutriplant": ["NUTR3"],
  "Melnick": ["MELK3"],
  "Mitre Realty": ["MTRE3"],
  "Rio Bravo": ["RBRA3"],
  "São Carlos": ["SCAR3"],
  "Wilson Sons": ["PORT3"],
  "Valid": ["VLID3"],
  "Battistella": ["BTTL3"],
  "Bardella": ["BDLL4"],
  "Kepler Weber": ["KEPL3"],
  "Romi": ["ROMI3"],
  "Teka": ["TEKA4"],
  "Tupy": ["TUPY3"],
  "Wetzel": ["MWET4"],
  "Açúcare Guarani": ["ACGU3"],
  "Cristal": ["CRPG6"],
  "Ferbasa": ["FESA4"],
  "Suzano Holding": ["NEMO3"],
  "Tupy": ["TUPY3"],
  "Vibra": ["VBBR3"],
  "Westwing": ["WEST3"],
  "Sinqia": ["SQIA3"],
  "Biotoscana": ["GBIO33"],
  "Dexco": ["DXCO3"],
  "Eternit": ["ETER3"],
  "Gafisa": ["GFSA3"],
  "Helbor": ["HBOR3"],
  "Jereissati": ["JPSA3"],
  "Lavvi": ["LAVV3"],
  "Moura Dubeux": ["MDNE3"],
  "Plascar": ["PLAS3"],
  "Tekno": ["TKNO4"],
  "Teka": ["TEKA4"],
  "Tenda": ["TEND3"],
  "Trisul": ["TRIS3"],
  "Viver": ["VIVR3"]
}