from typing import Protocol, Reversible
from .quest_types import EventRecord


class History(Protocol, Reversible):
    def append(self, item: EventRecord): ...

    def remove(self, item: EventRecord): ...

    def clear(self): ...

    def __iter__(self): ...

    def __reversed__(self): ...
