# coding: utf-8

"""
    Mycelium API

    Plex music collection and recommendation system using CLAP embeddings

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mycelium.api.generated_sources.server_schemas.models.stop_processing_response import StopProcessingResponse  # noqa: E501

class TestStopProcessingResponse(unittest.TestCase):
    """StopProcessingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StopProcessingResponse:
        """Test StopProcessingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StopProcessingResponse`
        """
        model = StopProcessingResponse()  # noqa: E501
        if include_optional:
            return StopProcessingResponse(
                message = '',
                type = '',
                cleared_tasks = 56
            )
        else:
            return StopProcessingResponse(
                message = '',
        )
        """

    def testStopProcessingResponse(self):
        """Test StopProcessingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
