# Generated by Django 5.2 on 2025-04-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_tasklog_env_tasklog_exception_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'verbose_name': 'Log de Tarefa', 'verbose_name_plural': 'Logs de Tarefas'},
        ),
    ]
