# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gateway

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DomainsStream(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DomainsStream()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDomainsStream(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DomainsStream
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DomainsStream
    def Domains(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # DomainsStream
    def DomainsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DomainsStream
    def DomainsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DomainsStreamStart(builder):
    builder.StartObject(1)

def Start(builder):
    DomainsStreamStart(builder)

def DomainsStreamAddDomains(builder, domains):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(domains), 0)

def AddDomains(builder, domains):
    DomainsStreamAddDomains(builder, domains)

def DomainsStreamStartDomainsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDomainsVector(builder, numElems):
    return DomainsStreamStartDomainsVector(builder, numElems)

def DomainsStreamEnd(builder):
    return builder.EndObject()

def End(builder):
    return DomainsStreamEnd(builder)
