"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import weaveapi.storage.v1.auth_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ObjectStore(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AWS_S3_FIELD_NUMBER: builtins.int
    AZURE_BLOB_STORAGE_FIELD_NUMBER: builtins.int
    GOOGLE_CLOUD_STORAGE_FIELD_NUMBER: builtins.int
    @property
    def aws_s3(self) -> global___AwsS3: ...
    @property
    def azure_blob_storage(self) -> global___AzureBlobStorage: ...
    @property
    def google_cloud_storage(self) -> global___GoogleCloudStorage: ...
    def __init__(
        self,
        *,
        aws_s3: global___AwsS3 | None = ...,
        azure_blob_storage: global___AzureBlobStorage | None = ...,
        google_cloud_storage: global___GoogleCloudStorage | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "aws_s3",
            b"aws_s3",
            "azure_blob_storage",
            b"azure_blob_storage",
            "google_cloud_storage",
            b"google_cloud_storage",
            "object_store",
            b"object_store",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aws_s3",
            b"aws_s3",
            "azure_blob_storage",
            b"azure_blob_storage",
            "google_cloud_storage",
            b"google_cloud_storage",
            "object_store",
            b"object_store",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["object_store", b"object_store"]
    ) -> (
        typing.Literal["aws_s3", "azure_blob_storage", "google_cloud_storage"] | None
    ): ...

global___ObjectStore = ObjectStore

@typing.final
class AwsS3(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    USE_INSTANCE_PROFILE_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    region: builtins.str
    use_instance_profile: builtins.bool
    @property
    def credentials(self) -> weaveapi.storage.v1.auth_pb2.AwsCredentials: ...
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        region: builtins.str = ...,
        credentials: weaveapi.storage.v1.auth_pb2.AwsCredentials | None = ...,
        use_instance_profile: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "auth",
            b"auth",
            "credentials",
            b"credentials",
            "use_instance_profile",
            b"use_instance_profile",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "auth",
            b"auth",
            "bucket",
            b"bucket",
            "credentials",
            b"credentials",
            "region",
            b"region",
            "use_instance_profile",
            b"use_instance_profile",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["auth", b"auth"]
    ) -> typing.Literal["credentials", "use_instance_profile"] | None: ...

global___AwsS3 = AwsS3

@typing.final
class AzureBlobStorage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTAINER_FIELD_NUMBER: builtins.int
    ACCOUNT_NAME_FIELD_NUMBER: builtins.int
    SAS_TOKEN_FIELD_NUMBER: builtins.int
    ACCOUNT_KEY_FIELD_NUMBER: builtins.int
    USE_MANAGED_IDENTITY_FIELD_NUMBER: builtins.int
    container: builtins.str
    account_name: builtins.str
    sas_token: builtins.str
    account_key: builtins.str
    use_managed_identity: builtins.bool
    def __init__(
        self,
        *,
        container: builtins.str = ...,
        account_name: builtins.str = ...,
        sas_token: builtins.str = ...,
        account_key: builtins.str = ...,
        use_managed_identity: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "account_key",
            b"account_key",
            "auth",
            b"auth",
            "sas_token",
            b"sas_token",
            "use_managed_identity",
            b"use_managed_identity",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "account_key",
            b"account_key",
            "account_name",
            b"account_name",
            "auth",
            b"auth",
            "container",
            b"container",
            "sas_token",
            b"sas_token",
            "use_managed_identity",
            b"use_managed_identity",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["auth", b"auth"]
    ) -> typing.Literal["sas_token", "account_key", "use_managed_identity"] | None: ...

global___AzureBlobStorage = AzureBlobStorage

@typing.final
class GoogleCloudStorage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    SERVICE_ACCOUNT_JSON_FIELD_NUMBER: builtins.int
    USE_APPLICATION_DEFAULT_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    service_account_json: builtins.str
    use_application_default: builtins.bool
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        service_account_json: builtins.str = ...,
        use_application_default: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "auth",
            b"auth",
            "service_account_json",
            b"service_account_json",
            "use_application_default",
            b"use_application_default",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "auth",
            b"auth",
            "bucket",
            b"bucket",
            "service_account_json",
            b"service_account_json",
            "use_application_default",
            b"use_application_default",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["auth", b"auth"]
    ) -> typing.Literal["service_account_json", "use_application_default"] | None: ...

global___GoogleCloudStorage = GoogleCloudStorage
