# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from weaveapi.payment.v1 import (
    service_pb2 as weaveapi_dot_payment_dot_v1_dot_service__pb2,
)


class PaymentStub(object):
    """PaymentService handles subscription management and payment processing
    Subscription management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCheckoutSession = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/CreateCheckoutSession",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionResponse.FromString,
            _registered_method=True,
        )
        self.GetSubscriptionStatus = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetSubscriptionStatus",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusResponse.FromString,
            _registered_method=True,
        )
        self.UpdateSubscription = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/UpdateSubscription",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.CancelSubscription = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/CancelSubscription",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.ResumeSubscription = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/ResumeSubscription",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.GetBillingHistory = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetBillingHistory",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryResponse.FromString,
            _registered_method=True,
        )
        self.GetUpcomingInvoice = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetUpcomingInvoice",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceResponse.FromString,
            _registered_method=True,
        )
        self.ListPaymentMethods = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/ListPaymentMethods",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsResponse.FromString,
            _registered_method=True,
        )
        self.AddPaymentMethod = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/AddPaymentMethod",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodResponse.FromString,
            _registered_method=True,
        )
        self.SetDefaultPaymentMethod = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/SetDefaultPaymentMethod",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodResponse.FromString,
            _registered_method=True,
        )
        self.RemovePaymentMethod = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/RemovePaymentMethod",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodResponse.FromString,
            _registered_method=True,
        )
        self.CreatePortalSession = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/CreatePortalSession",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionResponse.FromString,
            _registered_method=True,
        )
        self.GetPricingPlans = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetPricingPlans",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansResponse.FromString,
            _registered_method=True,
        )
        self.ApplyPromoCode = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/ApplyPromoCode",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeResponse.FromString,
            _registered_method=True,
        )
        self.HandleStripeWebhook = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/HandleStripeWebhook",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookResponse.FromString,
            _registered_method=True,
        )
        self.GetUsageSummary = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetUsageSummary",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryResponse.FromString,
            _registered_method=True,
        )
        self.GetCreditBalance = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/GetCreditBalance",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceResponse.FromString,
            _registered_method=True,
        )
        self.UpdateTaxInfo = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/UpdateTaxInfo",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoResponse.FromString,
            _registered_method=True,
        )
        self.DownloadInvoice = channel.unary_unary(
            "/weaveapi.payment.v1.Payment/DownloadInvoice",
            request_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceRequest.SerializeToString,
            response_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceResponse.FromString,
            _registered_method=True,
        )


class PaymentServicer(object):
    """PaymentService handles subscription management and payment processing
    Subscription management
    """

    def CreateCheckoutSession(self, request, context):
        """Create a Stripe checkout session for subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSubscriptionStatus(self, request, context):
        """Get current subscription status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSubscription(self, request, context):
        """Update subscription (change payment method, etc)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelSubscription(self, request, context):
        """Cancel subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResumeSubscription(self, request, context):
        """Resume cancelled subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBillingHistory(self, request, context):
        """Billing & Payment Methods

        Get billing history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUpcomingInvoice(self, request, context):
        """Get upcoming invoice preview"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPaymentMethods(self, request, context):
        """List payment methods"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddPaymentMethod(self, request, context):
        """Add payment method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetDefaultPaymentMethod(self, request, context):
        """Set default payment method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemovePaymentMethod(self, request, context):
        """Remove payment method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePortalSession(self, request, context):
        """Customer Portal

        Create Stripe customer portal session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPricingPlans(self, request, context):
        """Pricing & Plans

        Get available pricing plans
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyPromoCode(self, request, context):
        """Apply promo code"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HandleStripeWebhook(self, request, context):
        """Webhooks

        Handle Stripe webhook events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUsageSummary(self, request, context):
        """Usage & Credits

        Get usage summary for billing period
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCreditBalance(self, request, context):
        """Get credit balance (if applicable)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateTaxInfo(self, request, context):
        """Tax & Compliance

        Update tax information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DownloadInvoice(self, request, context):
        """Download invoice PDF"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PaymentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateCheckoutSession": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCheckoutSession,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionResponse.SerializeToString,
        ),
        "GetSubscriptionStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscriptionStatus,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusResponse.SerializeToString,
        ),
        "UpdateSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSubscription,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionResponse.SerializeToString,
        ),
        "CancelSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.CancelSubscription,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionResponse.SerializeToString,
        ),
        "ResumeSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.ResumeSubscription,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionResponse.SerializeToString,
        ),
        "GetBillingHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetBillingHistory,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryResponse.SerializeToString,
        ),
        "GetUpcomingInvoice": grpc.unary_unary_rpc_method_handler(
            servicer.GetUpcomingInvoice,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceResponse.SerializeToString,
        ),
        "ListPaymentMethods": grpc.unary_unary_rpc_method_handler(
            servicer.ListPaymentMethods,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsResponse.SerializeToString,
        ),
        "AddPaymentMethod": grpc.unary_unary_rpc_method_handler(
            servicer.AddPaymentMethod,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodResponse.SerializeToString,
        ),
        "SetDefaultPaymentMethod": grpc.unary_unary_rpc_method_handler(
            servicer.SetDefaultPaymentMethod,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodResponse.SerializeToString,
        ),
        "RemovePaymentMethod": grpc.unary_unary_rpc_method_handler(
            servicer.RemovePaymentMethod,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodResponse.SerializeToString,
        ),
        "CreatePortalSession": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePortalSession,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionResponse.SerializeToString,
        ),
        "GetPricingPlans": grpc.unary_unary_rpc_method_handler(
            servicer.GetPricingPlans,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansResponse.SerializeToString,
        ),
        "ApplyPromoCode": grpc.unary_unary_rpc_method_handler(
            servicer.ApplyPromoCode,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeResponse.SerializeToString,
        ),
        "HandleStripeWebhook": grpc.unary_unary_rpc_method_handler(
            servicer.HandleStripeWebhook,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookResponse.SerializeToString,
        ),
        "GetUsageSummary": grpc.unary_unary_rpc_method_handler(
            servicer.GetUsageSummary,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryResponse.SerializeToString,
        ),
        "GetCreditBalance": grpc.unary_unary_rpc_method_handler(
            servicer.GetCreditBalance,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceResponse.SerializeToString,
        ),
        "UpdateTaxInfo": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateTaxInfo,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoResponse.SerializeToString,
        ),
        "DownloadInvoice": grpc.unary_unary_rpc_method_handler(
            servicer.DownloadInvoice,
            request_deserializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceRequest.FromString,
            response_serializer=weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "weaveapi.payment.v1.Payment", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "weaveapi.payment.v1.Payment", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Payment(object):
    """PaymentService handles subscription management and payment processing
    Subscription management
    """

    @staticmethod
    def CreateCheckoutSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/CreateCheckoutSession",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CreateCheckoutSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSubscriptionStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetSubscriptionStatus",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetSubscriptionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/UpdateSubscription",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/CancelSubscription",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CancelSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResumeSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/ResumeSubscription",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ResumeSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBillingHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetBillingHistory",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetBillingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUpcomingInvoice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetUpcomingInvoice",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUpcomingInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPaymentMethods(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/ListPaymentMethods",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ListPaymentMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddPaymentMethod(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/AddPaymentMethod",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.AddPaymentMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetDefaultPaymentMethod(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/SetDefaultPaymentMethod",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.SetDefaultPaymentMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemovePaymentMethod(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/RemovePaymentMethod",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.RemovePaymentMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreatePortalSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/CreatePortalSession",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.CreatePortalSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPricingPlans(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetPricingPlans",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetPricingPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ApplyPromoCode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/ApplyPromoCode",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.ApplyPromoCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HandleStripeWebhook(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/HandleStripeWebhook",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.HandleStripeWebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUsageSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetUsageSummary",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetUsageSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCreditBalance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/GetCreditBalance",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.GetCreditBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateTaxInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/UpdateTaxInfo",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.UpdateTaxInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DownloadInvoice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/weaveapi.payment.v1.Payment/DownloadInvoice",
            weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceRequest.SerializeToString,
            weaveapi_dot_payment_dot_v1_dot_service__pb2.DownloadInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
