
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-09T18:02:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6be5ca8e2ce5ffb623ef1369b064023c5391d76b",
 "version": "0.43.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
