# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weaveapi/auth/v1/session.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 32, 0, "", "weaveapi/auth/v1/session.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1eweaveapi/auth/v1/session.proto\x12\x10weaveapi.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xc6\x03\n\x07Session\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x19\n\x08token_id\x18\x03 \x01(\tR\x07tokenId\x12\x1d\n\nip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n\nuser_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1a\n\x08location\x18\x06 \x01(\tR\x08location\x12\x1f\n\x0b\x64\x65vice_type\x18\x07 \x01(\tR\ndeviceType\x12\x1b\n\tis_active\x18\x08 \x01(\x08R\x08isActive\x12\x39\n\nexpires_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampR\texpiresAt\x12\x44\n\x10last_activity_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0elastActivityAt\x12#\n\rrequest_count\x18\x0b \x01(\x05R\x0crequestCount\x12\x39\n\ncreated_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtB\xbc\x01\n\x14\x63om.weaveapi.auth.v1B\x0cSessionProtoP\x01Z4github.com/weave-labs/weave-go/weaveapi/auth/v1;auth\xa2\x02\x03WAX\xaa\x02\x10Weaveapi.Auth.V1\xca\x02\x10Weaveapi\\Auth\\V1\xe2\x02\x1cWeaveapi\\Auth\\V1\\GPBMetadata\xea\x02\x12Weaveapi::Auth::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "weaveapi.auth.v1.session_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\024com.weaveapi.auth.v1B\014SessionProtoP\001Z4github.com/weave-labs/weave-go/weaveapi/auth/v1;auth\242\002\003WAX\252\002\020Weaveapi.Auth.V1\312\002\020Weaveapi\\Auth\\V1\342\002\034Weaveapi\\Auth\\V1\\GPBMetadata\352\002\022Weaveapi::Auth::V1"
    _globals["_SESSION"]._serialized_start = 86
    _globals["_SESSION"]._serialized_end = 540
# @@protoc_insertion_point(module_scope)
