"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OwnedByTypedDict(TypedDict):
    id: NotRequired[str]
    r"""The ID of the user that owns this resource."""
    user_name: NotRequired[str]
    r"""The resource owner's username."""
    first_name: NotRequired[str]
    r"""The resource owner's first name."""
    middle_name: NotRequired[str]
    r"""The resource owner's middle name."""
    last_name: NotRequired[str]
    r"""The resource owner's last name."""


class OwnedBy(BaseModel):
    id: Optional[str] = None
    r"""The ID of the user that owns this resource."""

    user_name: Annotated[Optional[str], pydantic.Field(alias="userName")] = None
    r"""The resource owner's username."""

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None
    r"""The resource owner's first name."""

    middle_name: Annotated[Optional[str], pydantic.Field(alias="middleName")] = None
    r"""The resource owner's middle name."""

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None
    r"""The resource owner's last name."""
