# Generated by Django 4.1.6 on 2024-03-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csembedlyparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedlyparsed',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='embedlyparsed',
            name='title_original',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='oembedsized',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csembedlyparser.embedlyparsed'),
        ),
    ]
