from _typeshed import Incomplete
from datahub.setting import SftpSetting
from paramiko import SFTPClient as _SFTPClient

__all__ = ['SFTPClient']

class SFTPClient:
    setting: Incomplete
    chmod: Incomplete
    ssh: Incomplete
    sftp: _SFTPClient
    def __init__(self, setting: SftpSetting, chmod: int = 509) -> None: ...
    def ensure_dir(self, dir_path: str, chmod: int = 509) -> bool: ...
    def rmdir_recursive(self, path: str): ...
    def connect(self): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
