from ..protos.client_msg import deserialize as deserialize, serialize as serialize
from _typeshed import Incomplete
from datahub.setting import RedisSetting as RedisSetting
from typing import Any, Iterator, Sequence

class RedisStream:
    client: Incomplete
    ident: Incomplete
    def __init__(self, setting: RedisSetting) -> None: ...
    def ensure_group(self, topics: Sequence[str]): ...
    def set_position(self, topic: str, posi: str): ...
    def read(self, topics: Sequence[str], count: int = 1, ignore_pending: bool = False, block: int = 0) -> Iterator[Any]: ...
    def write(self, topic: str, proto_msg: Any): ...
    def delete(self, topic: str): ...
    def ack(self, topic: str, message_id: str): ...
