"""
Setup script for types-aiobotocore-full.

Copyright 2025 Vlad Emelianov
"""

from pathlib import Path

from setuptools import setup  # type: ignore

LONG_DESCRIPTION = (Path(__file__).parent / "README.md").read_text()

setup(
    name="types-aiobotocore-full",
    version="2.25.0",
    packages=[
        "types_aiobotocore_accessanalyzer",
        "types_aiobotocore_account",
        "types_aiobotocore_acm",
        "types_aiobotocore_acm_pca",
        "types_aiobotocore_aiops",
        "types_aiobotocore_amp",
        "types_aiobotocore_amplify",
        "types_aiobotocore_amplifybackend",
        "types_aiobotocore_amplifyuibuilder",
        "types_aiobotocore_apigateway",
        "types_aiobotocore_apigatewaymanagementapi",
        "types_aiobotocore_apigatewayv2",
        "types_aiobotocore_appconfig",
        "types_aiobotocore_appconfigdata",
        "types_aiobotocore_appfabric",
        "types_aiobotocore_appflow",
        "types_aiobotocore_appintegrations",
        "types_aiobotocore_application_autoscaling",
        "types_aiobotocore_application_insights",
        "types_aiobotocore_application_signals",
        "types_aiobotocore_applicationcostprofiler",
        "types_aiobotocore_appmesh",
        "types_aiobotocore_apprunner",
        "types_aiobotocore_appstream",
        "types_aiobotocore_appsync",
        "types_aiobotocore_apptest",
        "types_aiobotocore_arc_region_switch",
        "types_aiobotocore_arc_zonal_shift",
        "types_aiobotocore_artifact",
        "types_aiobotocore_athena",
        "types_aiobotocore_auditmanager",
        "types_aiobotocore_autoscaling",
        "types_aiobotocore_autoscaling_plans",
        "types_aiobotocore_b2bi",
        "types_aiobotocore_backup",
        "types_aiobotocore_backup_gateway",
        "types_aiobotocore_backupsearch",
        "types_aiobotocore_batch",
        "types_aiobotocore_bcm_dashboards",
        "types_aiobotocore_bcm_data_exports",
        "types_aiobotocore_bcm_pricing_calculator",
        "types_aiobotocore_bcm_recommended_actions",
        "types_aiobotocore_bedrock",
        "types_aiobotocore_bedrock_agent",
        "types_aiobotocore_bedrock_agent_runtime",
        "types_aiobotocore_bedrock_agentcore",
        "types_aiobotocore_bedrock_agentcore_control",
        "types_aiobotocore_bedrock_data_automation",
        "types_aiobotocore_bedrock_data_automation_runtime",
        "types_aiobotocore_bedrock_runtime",
        "types_aiobotocore_billing",
        "types_aiobotocore_billingconductor",
        "types_aiobotocore_braket",
        "types_aiobotocore_budgets",
        "types_aiobotocore_ce",
        "types_aiobotocore_chatbot",
        "types_aiobotocore_chime",
        "types_aiobotocore_chime_sdk_identity",
        "types_aiobotocore_chime_sdk_media_pipelines",
        "types_aiobotocore_chime_sdk_meetings",
        "types_aiobotocore_chime_sdk_messaging",
        "types_aiobotocore_chime_sdk_voice",
        "types_aiobotocore_cleanrooms",
        "types_aiobotocore_cleanroomsml",
        "types_aiobotocore_cloud9",
        "types_aiobotocore_cloudcontrol",
        "types_aiobotocore_clouddirectory",
        "types_aiobotocore_cloudformation",
        "types_aiobotocore_cloudfront",
        "types_aiobotocore_cloudfront_keyvaluestore",
        "types_aiobotocore_cloudhsm",
        "types_aiobotocore_cloudhsmv2",
        "types_aiobotocore_cloudsearch",
        "types_aiobotocore_cloudsearchdomain",
        "types_aiobotocore_cloudtrail",
        "types_aiobotocore_cloudtrail_data",
        "types_aiobotocore_cloudwatch",
        "types_aiobotocore_codeartifact",
        "types_aiobotocore_codebuild",
        "types_aiobotocore_codecatalyst",
        "types_aiobotocore_codecommit",
        "types_aiobotocore_codeconnections",
        "types_aiobotocore_codedeploy",
        "types_aiobotocore_codeguru_reviewer",
        "types_aiobotocore_codeguru_security",
        "types_aiobotocore_codeguruprofiler",
        "types_aiobotocore_codepipeline",
        "types_aiobotocore_codestar_connections",
        "types_aiobotocore_codestar_notifications",
        "types_aiobotocore_cognito_identity",
        "types_aiobotocore_cognito_idp",
        "types_aiobotocore_cognito_sync",
        "types_aiobotocore_comprehend",
        "types_aiobotocore_comprehendmedical",
        "types_aiobotocore_compute_optimizer",
        "types_aiobotocore_config",
        "types_aiobotocore_connect",
        "types_aiobotocore_connect_contact_lens",
        "types_aiobotocore_connectcampaigns",
        "types_aiobotocore_connectcampaignsv2",
        "types_aiobotocore_connectcases",
        "types_aiobotocore_connectparticipant",
        "types_aiobotocore_controlcatalog",
        "types_aiobotocore_controltower",
        "types_aiobotocore_cost_optimization_hub",
        "types_aiobotocore_cur",
        "types_aiobotocore_customer_profiles",
        "types_aiobotocore_databrew",
        "types_aiobotocore_dataexchange",
        "types_aiobotocore_datapipeline",
        "types_aiobotocore_datasync",
        "types_aiobotocore_datazone",
        "types_aiobotocore_dax",
        "types_aiobotocore_deadline",
        "types_aiobotocore_detective",
        "types_aiobotocore_devicefarm",
        "types_aiobotocore_devops_guru",
        "types_aiobotocore_directconnect",
        "types_aiobotocore_discovery",
        "types_aiobotocore_dlm",
        "types_aiobotocore_dms",
        "types_aiobotocore_docdb",
        "types_aiobotocore_docdb_elastic",
        "types_aiobotocore_drs",
        "types_aiobotocore_ds",
        "types_aiobotocore_ds_data",
        "types_aiobotocore_dsql",
        "types_aiobotocore_dynamodb",
        "types_aiobotocore_dynamodbstreams",
        "types_aiobotocore_ebs",
        "types_aiobotocore_ec2",
        "types_aiobotocore_ec2_instance_connect",
        "types_aiobotocore_ecr",
        "types_aiobotocore_ecr_public",
        "types_aiobotocore_ecs",
        "types_aiobotocore_efs",
        "types_aiobotocore_eks",
        "types_aiobotocore_eks_auth",
        "types_aiobotocore_elasticache",
        "types_aiobotocore_elasticbeanstalk",
        "types_aiobotocore_elastictranscoder",
        "types_aiobotocore_elb",
        "types_aiobotocore_elbv2",
        "types_aiobotocore_emr",
        "types_aiobotocore_emr_containers",
        "types_aiobotocore_emr_serverless",
        "types_aiobotocore_entityresolution",
        "types_aiobotocore_es",
        "types_aiobotocore_events",
        "types_aiobotocore_evidently",
        "types_aiobotocore_evs",
        "types_aiobotocore_finspace",
        "types_aiobotocore_finspace_data",
        "types_aiobotocore_firehose",
        "types_aiobotocore_fis",
        "types_aiobotocore_fms",
        "types_aiobotocore_forecast",
        "types_aiobotocore_forecastquery",
        "types_aiobotocore_frauddetector",
        "types_aiobotocore_freetier",
        "types_aiobotocore_fsx",
        "types_aiobotocore_gamelift",
        "types_aiobotocore_gameliftstreams",
        "types_aiobotocore_geo_maps",
        "types_aiobotocore_geo_places",
        "types_aiobotocore_geo_routes",
        "types_aiobotocore_glacier",
        "types_aiobotocore_globalaccelerator",
        "types_aiobotocore_glue",
        "types_aiobotocore_grafana",
        "types_aiobotocore_greengrass",
        "types_aiobotocore_greengrassv2",
        "types_aiobotocore_groundstation",
        "types_aiobotocore_guardduty",
        "types_aiobotocore_health",
        "types_aiobotocore_healthlake",
        "types_aiobotocore_iam",
        "types_aiobotocore_identitystore",
        "types_aiobotocore_imagebuilder",
        "types_aiobotocore_importexport",
        "types_aiobotocore_inspector",
        "types_aiobotocore_inspector_scan",
        "types_aiobotocore_inspector2",
        "types_aiobotocore_internetmonitor",
        "types_aiobotocore_invoicing",
        "types_aiobotocore_iot",
        "types_aiobotocore_iot_data",
        "types_aiobotocore_iot_jobs_data",
        "types_aiobotocore_iot_managed_integrations",
        "types_aiobotocore_iotanalytics",
        "types_aiobotocore_iotdeviceadvisor",
        "types_aiobotocore_iotevents",
        "types_aiobotocore_iotevents_data",
        "types_aiobotocore_iotfleethub",
        "types_aiobotocore_iotfleetwise",
        "types_aiobotocore_iotsecuretunneling",
        "types_aiobotocore_iotsitewise",
        "types_aiobotocore_iotthingsgraph",
        "types_aiobotocore_iottwinmaker",
        "types_aiobotocore_iotwireless",
        "types_aiobotocore_ivs",
        "types_aiobotocore_ivs_realtime",
        "types_aiobotocore_ivschat",
        "types_aiobotocore_kafka",
        "types_aiobotocore_kafkaconnect",
        "types_aiobotocore_kendra",
        "types_aiobotocore_kendra_ranking",
        "types_aiobotocore_keyspaces",
        "types_aiobotocore_keyspacesstreams",
        "types_aiobotocore_kinesis",
        "types_aiobotocore_kinesis_video_archived_media",
        "types_aiobotocore_kinesis_video_media",
        "types_aiobotocore_kinesis_video_signaling",
        "types_aiobotocore_kinesis_video_webrtc_storage",
        "types_aiobotocore_kinesisanalytics",
        "types_aiobotocore_kinesisanalyticsv2",
        "types_aiobotocore_kinesisvideo",
        "types_aiobotocore_kms",
        "types_aiobotocore_lakeformation",
        "types_aiobotocore_lambda",
        "types_aiobotocore_launch_wizard",
        "types_aiobotocore_lex_models",
        "types_aiobotocore_lex_runtime",
        "types_aiobotocore_lexv2_models",
        "types_aiobotocore_lexv2_runtime",
        "types_aiobotocore_license_manager",
        "types_aiobotocore_license_manager_linux_subscriptions",
        "types_aiobotocore_license_manager_user_subscriptions",
        "types_aiobotocore_lightsail",
        "types_aiobotocore_location",
        "types_aiobotocore_logs",
        "types_aiobotocore_lookoutequipment",
        "types_aiobotocore_lookoutmetrics",
        "types_aiobotocore_lookoutvision",
        "types_aiobotocore_m2",
        "types_aiobotocore_machinelearning",
        "types_aiobotocore_macie2",
        "types_aiobotocore_mailmanager",
        "types_aiobotocore_managedblockchain",
        "types_aiobotocore_managedblockchain_query",
        "types_aiobotocore_marketplace_agreement",
        "types_aiobotocore_marketplace_catalog",
        "types_aiobotocore_marketplace_deployment",
        "types_aiobotocore_marketplace_entitlement",
        "types_aiobotocore_marketplace_reporting",
        "types_aiobotocore_marketplacecommerceanalytics",
        "types_aiobotocore_mediaconnect",
        "types_aiobotocore_mediaconvert",
        "types_aiobotocore_medialive",
        "types_aiobotocore_mediapackage",
        "types_aiobotocore_mediapackage_vod",
        "types_aiobotocore_mediapackagev2",
        "types_aiobotocore_mediastore",
        "types_aiobotocore_mediastore_data",
        "types_aiobotocore_mediatailor",
        "types_aiobotocore_medical_imaging",
        "types_aiobotocore_memorydb",
        "types_aiobotocore_meteringmarketplace",
        "types_aiobotocore_mgh",
        "types_aiobotocore_mgn",
        "types_aiobotocore_migration_hub_refactor_spaces",
        "types_aiobotocore_migrationhub_config",
        "types_aiobotocore_migrationhuborchestrator",
        "types_aiobotocore_migrationhubstrategy",
        "types_aiobotocore_mpa",
        "types_aiobotocore_mq",
        "types_aiobotocore_mturk",
        "types_aiobotocore_mwaa",
        "types_aiobotocore_neptune",
        "types_aiobotocore_neptune_graph",
        "types_aiobotocore_neptunedata",
        "types_aiobotocore_network_firewall",
        "types_aiobotocore_networkflowmonitor",
        "types_aiobotocore_networkmanager",
        "types_aiobotocore_networkmonitor",
        "types_aiobotocore_notifications",
        "types_aiobotocore_notificationscontacts",
        "types_aiobotocore_oam",
        "types_aiobotocore_observabilityadmin",
        "types_aiobotocore_odb",
        "types_aiobotocore_omics",
        "types_aiobotocore_opensearch",
        "types_aiobotocore_opensearchserverless",
        "types_aiobotocore_organizations",
        "types_aiobotocore_osis",
        "types_aiobotocore_outposts",
        "types_aiobotocore_panorama",
        "types_aiobotocore_partnercentral_selling",
        "types_aiobotocore_payment_cryptography",
        "types_aiobotocore_payment_cryptography_data",
        "types_aiobotocore_pca_connector_ad",
        "types_aiobotocore_pca_connector_scep",
        "types_aiobotocore_pcs",
        "types_aiobotocore_personalize",
        "types_aiobotocore_personalize_events",
        "types_aiobotocore_personalize_runtime",
        "types_aiobotocore_pi",
        "types_aiobotocore_pinpoint",
        "types_aiobotocore_pinpoint_email",
        "types_aiobotocore_pinpoint_sms_voice",
        "types_aiobotocore_pinpoint_sms_voice_v2",
        "types_aiobotocore_pipes",
        "types_aiobotocore_polly",
        "types_aiobotocore_pricing",
        "types_aiobotocore_proton",
        "types_aiobotocore_qapps",
        "types_aiobotocore_qbusiness",
        "types_aiobotocore_qconnect",
        "types_aiobotocore_qldb",
        "types_aiobotocore_qldb_session",
        "types_aiobotocore_quicksight",
        "types_aiobotocore_ram",
        "types_aiobotocore_rbin",
        "types_aiobotocore_rds",
        "types_aiobotocore_rds_data",
        "types_aiobotocore_redshift",
        "types_aiobotocore_redshift_data",
        "types_aiobotocore_redshift_serverless",
        "types_aiobotocore_rekognition",
        "types_aiobotocore_repostspace",
        "types_aiobotocore_resiliencehub",
        "types_aiobotocore_resource_explorer_2",
        "types_aiobotocore_resource_groups",
        "types_aiobotocore_resourcegroupstaggingapi",
        "types_aiobotocore_robomaker",
        "types_aiobotocore_rolesanywhere",
        "types_aiobotocore_route53",
        "types_aiobotocore_route53_recovery_cluster",
        "types_aiobotocore_route53_recovery_control_config",
        "types_aiobotocore_route53_recovery_readiness",
        "types_aiobotocore_route53domains",
        "types_aiobotocore_route53profiles",
        "types_aiobotocore_route53resolver",
        "types_aiobotocore_rum",
        "types_aiobotocore_s3",
        "types_aiobotocore_s3control",
        "types_aiobotocore_s3outposts",
        "types_aiobotocore_s3tables",
        "types_aiobotocore_s3vectors",
        "types_aiobotocore_sagemaker",
        "types_aiobotocore_sagemaker_a2i_runtime",
        "types_aiobotocore_sagemaker_edge",
        "types_aiobotocore_sagemaker_featurestore_runtime",
        "types_aiobotocore_sagemaker_geospatial",
        "types_aiobotocore_sagemaker_metrics",
        "types_aiobotocore_sagemaker_runtime",
        "types_aiobotocore_savingsplans",
        "types_aiobotocore_scheduler",
        "types_aiobotocore_schemas",
        "types_aiobotocore_sdb",
        "types_aiobotocore_secretsmanager",
        "types_aiobotocore_security_ir",
        "types_aiobotocore_securityhub",
        "types_aiobotocore_securitylake",
        "types_aiobotocore_serverlessrepo",
        "types_aiobotocore_service_quotas",
        "types_aiobotocore_servicecatalog",
        "types_aiobotocore_servicecatalog_appregistry",
        "types_aiobotocore_servicediscovery",
        "types_aiobotocore_ses",
        "types_aiobotocore_sesv2",
        "types_aiobotocore_shield",
        "types_aiobotocore_signer",
        "types_aiobotocore_simspaceweaver",
        "types_aiobotocore_snow_device_management",
        "types_aiobotocore_snowball",
        "types_aiobotocore_sns",
        "types_aiobotocore_socialmessaging",
        "types_aiobotocore_sqs",
        "types_aiobotocore_ssm",
        "types_aiobotocore_ssm_contacts",
        "types_aiobotocore_ssm_guiconnect",
        "types_aiobotocore_ssm_incidents",
        "types_aiobotocore_ssm_quicksetup",
        "types_aiobotocore_ssm_sap",
        "types_aiobotocore_sso",
        "types_aiobotocore_sso_admin",
        "types_aiobotocore_sso_oidc",
        "types_aiobotocore_stepfunctions",
        "types_aiobotocore_storagegateway",
        "types_aiobotocore_sts",
        "types_aiobotocore_supplychain",
        "types_aiobotocore_support",
        "types_aiobotocore_support_app",
        "types_aiobotocore_swf",
        "types_aiobotocore_synthetics",
        "types_aiobotocore_taxsettings",
        "types_aiobotocore_textract",
        "types_aiobotocore_timestream_influxdb",
        "types_aiobotocore_timestream_query",
        "types_aiobotocore_timestream_write",
        "types_aiobotocore_tnb",
        "types_aiobotocore_transcribe",
        "types_aiobotocore_transfer",
        "types_aiobotocore_translate",
        "types_aiobotocore_trustedadvisor",
        "types_aiobotocore_verifiedpermissions",
        "types_aiobotocore_voice_id",
        "types_aiobotocore_vpc_lattice",
        "types_aiobotocore_waf",
        "types_aiobotocore_waf_regional",
        "types_aiobotocore_wafv2",
        "types_aiobotocore_wellarchitected",
        "types_aiobotocore_wisdom",
        "types_aiobotocore_workdocs",
        "types_aiobotocore_workmail",
        "types_aiobotocore_workmailmessageflow",
        "types_aiobotocore_workspaces",
        "types_aiobotocore_workspaces_instances",
        "types_aiobotocore_workspaces_thin_client",
        "types_aiobotocore_workspaces_web",
        "types_aiobotocore_xray",
    ],
    url="https://github.com/youtype/mypy_boto3_builder",
    license="MIT License",
    author="Vlad Emelianov",
    author_email="vlad.emelianov.nz@gmail.com",
    description="All-in-one type annotations for aiobotocore 2.25.0 generated with mypy-boto3-builder 8.11.0",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Environment :: Console",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: Implementation :: CPython",
        "Typing :: Stubs Only",
    ],
    keywords="aiobotocore aiobotocore-stubs type-annotations typeshed autocomplete",
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    package_data={
        "types_aiobotocore_accessanalyzer": ["py.typed", "*.pyi"],
        "types_aiobotocore_account": ["py.typed", "*.pyi"],
        "types_aiobotocore_acm": ["py.typed", "*.pyi"],
        "types_aiobotocore_acm_pca": ["py.typed", "*.pyi"],
        "types_aiobotocore_aiops": ["py.typed", "*.pyi"],
        "types_aiobotocore_amp": ["py.typed", "*.pyi"],
        "types_aiobotocore_amplify": ["py.typed", "*.pyi"],
        "types_aiobotocore_amplifybackend": ["py.typed", "*.pyi"],
        "types_aiobotocore_amplifyuibuilder": ["py.typed", "*.pyi"],
        "types_aiobotocore_apigateway": ["py.typed", "*.pyi"],
        "types_aiobotocore_apigatewaymanagementapi": ["py.typed", "*.pyi"],
        "types_aiobotocore_apigatewayv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_appconfig": ["py.typed", "*.pyi"],
        "types_aiobotocore_appconfigdata": ["py.typed", "*.pyi"],
        "types_aiobotocore_appfabric": ["py.typed", "*.pyi"],
        "types_aiobotocore_appflow": ["py.typed", "*.pyi"],
        "types_aiobotocore_appintegrations": ["py.typed", "*.pyi"],
        "types_aiobotocore_application_autoscaling": ["py.typed", "*.pyi"],
        "types_aiobotocore_application_insights": ["py.typed", "*.pyi"],
        "types_aiobotocore_application_signals": ["py.typed", "*.pyi"],
        "types_aiobotocore_applicationcostprofiler": ["py.typed", "*.pyi"],
        "types_aiobotocore_appmesh": ["py.typed", "*.pyi"],
        "types_aiobotocore_apprunner": ["py.typed", "*.pyi"],
        "types_aiobotocore_appstream": ["py.typed", "*.pyi"],
        "types_aiobotocore_appsync": ["py.typed", "*.pyi"],
        "types_aiobotocore_apptest": ["py.typed", "*.pyi"],
        "types_aiobotocore_arc_region_switch": ["py.typed", "*.pyi"],
        "types_aiobotocore_arc_zonal_shift": ["py.typed", "*.pyi"],
        "types_aiobotocore_artifact": ["py.typed", "*.pyi"],
        "types_aiobotocore_athena": ["py.typed", "*.pyi"],
        "types_aiobotocore_auditmanager": ["py.typed", "*.pyi"],
        "types_aiobotocore_autoscaling": ["py.typed", "*.pyi"],
        "types_aiobotocore_autoscaling_plans": ["py.typed", "*.pyi"],
        "types_aiobotocore_b2bi": ["py.typed", "*.pyi"],
        "types_aiobotocore_backup": ["py.typed", "*.pyi"],
        "types_aiobotocore_backup_gateway": ["py.typed", "*.pyi"],
        "types_aiobotocore_backupsearch": ["py.typed", "*.pyi"],
        "types_aiobotocore_batch": ["py.typed", "*.pyi"],
        "types_aiobotocore_bcm_dashboards": ["py.typed", "*.pyi"],
        "types_aiobotocore_bcm_data_exports": ["py.typed", "*.pyi"],
        "types_aiobotocore_bcm_pricing_calculator": ["py.typed", "*.pyi"],
        "types_aiobotocore_bcm_recommended_actions": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_agent": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_agent_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_agentcore": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_agentcore_control": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_data_automation": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_data_automation_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_bedrock_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_billing": ["py.typed", "*.pyi"],
        "types_aiobotocore_billingconductor": ["py.typed", "*.pyi"],
        "types_aiobotocore_braket": ["py.typed", "*.pyi"],
        "types_aiobotocore_budgets": ["py.typed", "*.pyi"],
        "types_aiobotocore_ce": ["py.typed", "*.pyi"],
        "types_aiobotocore_chatbot": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime_sdk_identity": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime_sdk_media_pipelines": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime_sdk_meetings": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime_sdk_messaging": ["py.typed", "*.pyi"],
        "types_aiobotocore_chime_sdk_voice": ["py.typed", "*.pyi"],
        "types_aiobotocore_cleanrooms": ["py.typed", "*.pyi"],
        "types_aiobotocore_cleanroomsml": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloud9": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudcontrol": ["py.typed", "*.pyi"],
        "types_aiobotocore_clouddirectory": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudformation": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudfront": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudfront_keyvaluestore": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudhsm": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudhsmv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudsearch": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudsearchdomain": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudtrail": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudtrail_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_cloudwatch": ["py.typed", "*.pyi"],
        "types_aiobotocore_codeartifact": ["py.typed", "*.pyi"],
        "types_aiobotocore_codebuild": ["py.typed", "*.pyi"],
        "types_aiobotocore_codecatalyst": ["py.typed", "*.pyi"],
        "types_aiobotocore_codecommit": ["py.typed", "*.pyi"],
        "types_aiobotocore_codeconnections": ["py.typed", "*.pyi"],
        "types_aiobotocore_codedeploy": ["py.typed", "*.pyi"],
        "types_aiobotocore_codeguru_reviewer": ["py.typed", "*.pyi"],
        "types_aiobotocore_codeguru_security": ["py.typed", "*.pyi"],
        "types_aiobotocore_codeguruprofiler": ["py.typed", "*.pyi"],
        "types_aiobotocore_codepipeline": ["py.typed", "*.pyi"],
        "types_aiobotocore_codestar_connections": ["py.typed", "*.pyi"],
        "types_aiobotocore_codestar_notifications": ["py.typed", "*.pyi"],
        "types_aiobotocore_cognito_identity": ["py.typed", "*.pyi"],
        "types_aiobotocore_cognito_idp": ["py.typed", "*.pyi"],
        "types_aiobotocore_cognito_sync": ["py.typed", "*.pyi"],
        "types_aiobotocore_comprehend": ["py.typed", "*.pyi"],
        "types_aiobotocore_comprehendmedical": ["py.typed", "*.pyi"],
        "types_aiobotocore_compute_optimizer": ["py.typed", "*.pyi"],
        "types_aiobotocore_config": ["py.typed", "*.pyi"],
        "types_aiobotocore_connect": ["py.typed", "*.pyi"],
        "types_aiobotocore_connect_contact_lens": ["py.typed", "*.pyi"],
        "types_aiobotocore_connectcampaigns": ["py.typed", "*.pyi"],
        "types_aiobotocore_connectcampaignsv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_connectcases": ["py.typed", "*.pyi"],
        "types_aiobotocore_connectparticipant": ["py.typed", "*.pyi"],
        "types_aiobotocore_controlcatalog": ["py.typed", "*.pyi"],
        "types_aiobotocore_controltower": ["py.typed", "*.pyi"],
        "types_aiobotocore_cost_optimization_hub": ["py.typed", "*.pyi"],
        "types_aiobotocore_cur": ["py.typed", "*.pyi"],
        "types_aiobotocore_customer_profiles": ["py.typed", "*.pyi"],
        "types_aiobotocore_databrew": ["py.typed", "*.pyi"],
        "types_aiobotocore_dataexchange": ["py.typed", "*.pyi"],
        "types_aiobotocore_datapipeline": ["py.typed", "*.pyi"],
        "types_aiobotocore_datasync": ["py.typed", "*.pyi"],
        "types_aiobotocore_datazone": ["py.typed", "*.pyi"],
        "types_aiobotocore_dax": ["py.typed", "*.pyi"],
        "types_aiobotocore_deadline": ["py.typed", "*.pyi"],
        "types_aiobotocore_detective": ["py.typed", "*.pyi"],
        "types_aiobotocore_devicefarm": ["py.typed", "*.pyi"],
        "types_aiobotocore_devops_guru": ["py.typed", "*.pyi"],
        "types_aiobotocore_directconnect": ["py.typed", "*.pyi"],
        "types_aiobotocore_discovery": ["py.typed", "*.pyi"],
        "types_aiobotocore_dlm": ["py.typed", "*.pyi"],
        "types_aiobotocore_dms": ["py.typed", "*.pyi"],
        "types_aiobotocore_docdb": ["py.typed", "*.pyi"],
        "types_aiobotocore_docdb_elastic": ["py.typed", "*.pyi"],
        "types_aiobotocore_drs": ["py.typed", "*.pyi"],
        "types_aiobotocore_ds": ["py.typed", "*.pyi"],
        "types_aiobotocore_ds_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_dsql": ["py.typed", "*.pyi"],
        "types_aiobotocore_dynamodb": ["py.typed", "*.pyi"],
        "types_aiobotocore_dynamodbstreams": ["py.typed", "*.pyi"],
        "types_aiobotocore_ebs": ["py.typed", "*.pyi"],
        "types_aiobotocore_ec2": ["py.typed", "*.pyi"],
        "types_aiobotocore_ec2_instance_connect": ["py.typed", "*.pyi"],
        "types_aiobotocore_ecr": ["py.typed", "*.pyi"],
        "types_aiobotocore_ecr_public": ["py.typed", "*.pyi"],
        "types_aiobotocore_ecs": ["py.typed", "*.pyi"],
        "types_aiobotocore_efs": ["py.typed", "*.pyi"],
        "types_aiobotocore_eks": ["py.typed", "*.pyi"],
        "types_aiobotocore_eks_auth": ["py.typed", "*.pyi"],
        "types_aiobotocore_elasticache": ["py.typed", "*.pyi"],
        "types_aiobotocore_elasticbeanstalk": ["py.typed", "*.pyi"],
        "types_aiobotocore_elastictranscoder": ["py.typed", "*.pyi"],
        "types_aiobotocore_elb": ["py.typed", "*.pyi"],
        "types_aiobotocore_elbv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_emr": ["py.typed", "*.pyi"],
        "types_aiobotocore_emr_containers": ["py.typed", "*.pyi"],
        "types_aiobotocore_emr_serverless": ["py.typed", "*.pyi"],
        "types_aiobotocore_entityresolution": ["py.typed", "*.pyi"],
        "types_aiobotocore_es": ["py.typed", "*.pyi"],
        "types_aiobotocore_events": ["py.typed", "*.pyi"],
        "types_aiobotocore_evidently": ["py.typed", "*.pyi"],
        "types_aiobotocore_evs": ["py.typed", "*.pyi"],
        "types_aiobotocore_finspace": ["py.typed", "*.pyi"],
        "types_aiobotocore_finspace_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_firehose": ["py.typed", "*.pyi"],
        "types_aiobotocore_fis": ["py.typed", "*.pyi"],
        "types_aiobotocore_fms": ["py.typed", "*.pyi"],
        "types_aiobotocore_forecast": ["py.typed", "*.pyi"],
        "types_aiobotocore_forecastquery": ["py.typed", "*.pyi"],
        "types_aiobotocore_frauddetector": ["py.typed", "*.pyi"],
        "types_aiobotocore_freetier": ["py.typed", "*.pyi"],
        "types_aiobotocore_fsx": ["py.typed", "*.pyi"],
        "types_aiobotocore_gamelift": ["py.typed", "*.pyi"],
        "types_aiobotocore_gameliftstreams": ["py.typed", "*.pyi"],
        "types_aiobotocore_geo_maps": ["py.typed", "*.pyi"],
        "types_aiobotocore_geo_places": ["py.typed", "*.pyi"],
        "types_aiobotocore_geo_routes": ["py.typed", "*.pyi"],
        "types_aiobotocore_glacier": ["py.typed", "*.pyi"],
        "types_aiobotocore_globalaccelerator": ["py.typed", "*.pyi"],
        "types_aiobotocore_glue": ["py.typed", "*.pyi"],
        "types_aiobotocore_grafana": ["py.typed", "*.pyi"],
        "types_aiobotocore_greengrass": ["py.typed", "*.pyi"],
        "types_aiobotocore_greengrassv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_groundstation": ["py.typed", "*.pyi"],
        "types_aiobotocore_guardduty": ["py.typed", "*.pyi"],
        "types_aiobotocore_health": ["py.typed", "*.pyi"],
        "types_aiobotocore_healthlake": ["py.typed", "*.pyi"],
        "types_aiobotocore_iam": ["py.typed", "*.pyi"],
        "types_aiobotocore_identitystore": ["py.typed", "*.pyi"],
        "types_aiobotocore_imagebuilder": ["py.typed", "*.pyi"],
        "types_aiobotocore_importexport": ["py.typed", "*.pyi"],
        "types_aiobotocore_inspector": ["py.typed", "*.pyi"],
        "types_aiobotocore_inspector_scan": ["py.typed", "*.pyi"],
        "types_aiobotocore_inspector2": ["py.typed", "*.pyi"],
        "types_aiobotocore_internetmonitor": ["py.typed", "*.pyi"],
        "types_aiobotocore_invoicing": ["py.typed", "*.pyi"],
        "types_aiobotocore_iot": ["py.typed", "*.pyi"],
        "types_aiobotocore_iot_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_iot_jobs_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_iot_managed_integrations": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotanalytics": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotdeviceadvisor": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotevents": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotevents_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotfleethub": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotfleetwise": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotsecuretunneling": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotsitewise": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotthingsgraph": ["py.typed", "*.pyi"],
        "types_aiobotocore_iottwinmaker": ["py.typed", "*.pyi"],
        "types_aiobotocore_iotwireless": ["py.typed", "*.pyi"],
        "types_aiobotocore_ivs": ["py.typed", "*.pyi"],
        "types_aiobotocore_ivs_realtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_ivschat": ["py.typed", "*.pyi"],
        "types_aiobotocore_kafka": ["py.typed", "*.pyi"],
        "types_aiobotocore_kafkaconnect": ["py.typed", "*.pyi"],
        "types_aiobotocore_kendra": ["py.typed", "*.pyi"],
        "types_aiobotocore_kendra_ranking": ["py.typed", "*.pyi"],
        "types_aiobotocore_keyspaces": ["py.typed", "*.pyi"],
        "types_aiobotocore_keyspacesstreams": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesis": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesis_video_archived_media": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesis_video_media": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesis_video_signaling": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesis_video_webrtc_storage": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesisanalytics": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesisanalyticsv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_kinesisvideo": ["py.typed", "*.pyi"],
        "types_aiobotocore_kms": ["py.typed", "*.pyi"],
        "types_aiobotocore_lakeformation": ["py.typed", "*.pyi"],
        "types_aiobotocore_lambda": ["py.typed", "*.pyi"],
        "types_aiobotocore_launch_wizard": ["py.typed", "*.pyi"],
        "types_aiobotocore_lex_models": ["py.typed", "*.pyi"],
        "types_aiobotocore_lex_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_lexv2_models": ["py.typed", "*.pyi"],
        "types_aiobotocore_lexv2_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_license_manager": ["py.typed", "*.pyi"],
        "types_aiobotocore_license_manager_linux_subscriptions": ["py.typed", "*.pyi"],
        "types_aiobotocore_license_manager_user_subscriptions": ["py.typed", "*.pyi"],
        "types_aiobotocore_lightsail": ["py.typed", "*.pyi"],
        "types_aiobotocore_location": ["py.typed", "*.pyi"],
        "types_aiobotocore_logs": ["py.typed", "*.pyi"],
        "types_aiobotocore_lookoutequipment": ["py.typed", "*.pyi"],
        "types_aiobotocore_lookoutmetrics": ["py.typed", "*.pyi"],
        "types_aiobotocore_lookoutvision": ["py.typed", "*.pyi"],
        "types_aiobotocore_m2": ["py.typed", "*.pyi"],
        "types_aiobotocore_machinelearning": ["py.typed", "*.pyi"],
        "types_aiobotocore_macie2": ["py.typed", "*.pyi"],
        "types_aiobotocore_mailmanager": ["py.typed", "*.pyi"],
        "types_aiobotocore_managedblockchain": ["py.typed", "*.pyi"],
        "types_aiobotocore_managedblockchain_query": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplace_agreement": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplace_catalog": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplace_deployment": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplace_entitlement": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplace_reporting": ["py.typed", "*.pyi"],
        "types_aiobotocore_marketplacecommerceanalytics": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediaconnect": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediaconvert": ["py.typed", "*.pyi"],
        "types_aiobotocore_medialive": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediapackage": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediapackage_vod": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediapackagev2": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediastore": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediastore_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_mediatailor": ["py.typed", "*.pyi"],
        "types_aiobotocore_medical_imaging": ["py.typed", "*.pyi"],
        "types_aiobotocore_memorydb": ["py.typed", "*.pyi"],
        "types_aiobotocore_meteringmarketplace": ["py.typed", "*.pyi"],
        "types_aiobotocore_mgh": ["py.typed", "*.pyi"],
        "types_aiobotocore_mgn": ["py.typed", "*.pyi"],
        "types_aiobotocore_migration_hub_refactor_spaces": ["py.typed", "*.pyi"],
        "types_aiobotocore_migrationhub_config": ["py.typed", "*.pyi"],
        "types_aiobotocore_migrationhuborchestrator": ["py.typed", "*.pyi"],
        "types_aiobotocore_migrationhubstrategy": ["py.typed", "*.pyi"],
        "types_aiobotocore_mpa": ["py.typed", "*.pyi"],
        "types_aiobotocore_mq": ["py.typed", "*.pyi"],
        "types_aiobotocore_mturk": ["py.typed", "*.pyi"],
        "types_aiobotocore_mwaa": ["py.typed", "*.pyi"],
        "types_aiobotocore_neptune": ["py.typed", "*.pyi"],
        "types_aiobotocore_neptune_graph": ["py.typed", "*.pyi"],
        "types_aiobotocore_neptunedata": ["py.typed", "*.pyi"],
        "types_aiobotocore_network_firewall": ["py.typed", "*.pyi"],
        "types_aiobotocore_networkflowmonitor": ["py.typed", "*.pyi"],
        "types_aiobotocore_networkmanager": ["py.typed", "*.pyi"],
        "types_aiobotocore_networkmonitor": ["py.typed", "*.pyi"],
        "types_aiobotocore_notifications": ["py.typed", "*.pyi"],
        "types_aiobotocore_notificationscontacts": ["py.typed", "*.pyi"],
        "types_aiobotocore_oam": ["py.typed", "*.pyi"],
        "types_aiobotocore_observabilityadmin": ["py.typed", "*.pyi"],
        "types_aiobotocore_odb": ["py.typed", "*.pyi"],
        "types_aiobotocore_omics": ["py.typed", "*.pyi"],
        "types_aiobotocore_opensearch": ["py.typed", "*.pyi"],
        "types_aiobotocore_opensearchserverless": ["py.typed", "*.pyi"],
        "types_aiobotocore_organizations": ["py.typed", "*.pyi"],
        "types_aiobotocore_osis": ["py.typed", "*.pyi"],
        "types_aiobotocore_outposts": ["py.typed", "*.pyi"],
        "types_aiobotocore_panorama": ["py.typed", "*.pyi"],
        "types_aiobotocore_partnercentral_selling": ["py.typed", "*.pyi"],
        "types_aiobotocore_payment_cryptography": ["py.typed", "*.pyi"],
        "types_aiobotocore_payment_cryptography_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_pca_connector_ad": ["py.typed", "*.pyi"],
        "types_aiobotocore_pca_connector_scep": ["py.typed", "*.pyi"],
        "types_aiobotocore_pcs": ["py.typed", "*.pyi"],
        "types_aiobotocore_personalize": ["py.typed", "*.pyi"],
        "types_aiobotocore_personalize_events": ["py.typed", "*.pyi"],
        "types_aiobotocore_personalize_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_pi": ["py.typed", "*.pyi"],
        "types_aiobotocore_pinpoint": ["py.typed", "*.pyi"],
        "types_aiobotocore_pinpoint_email": ["py.typed", "*.pyi"],
        "types_aiobotocore_pinpoint_sms_voice": ["py.typed", "*.pyi"],
        "types_aiobotocore_pinpoint_sms_voice_v2": ["py.typed", "*.pyi"],
        "types_aiobotocore_pipes": ["py.typed", "*.pyi"],
        "types_aiobotocore_polly": ["py.typed", "*.pyi"],
        "types_aiobotocore_pricing": ["py.typed", "*.pyi"],
        "types_aiobotocore_proton": ["py.typed", "*.pyi"],
        "types_aiobotocore_qapps": ["py.typed", "*.pyi"],
        "types_aiobotocore_qbusiness": ["py.typed", "*.pyi"],
        "types_aiobotocore_qconnect": ["py.typed", "*.pyi"],
        "types_aiobotocore_qldb": ["py.typed", "*.pyi"],
        "types_aiobotocore_qldb_session": ["py.typed", "*.pyi"],
        "types_aiobotocore_quicksight": ["py.typed", "*.pyi"],
        "types_aiobotocore_ram": ["py.typed", "*.pyi"],
        "types_aiobotocore_rbin": ["py.typed", "*.pyi"],
        "types_aiobotocore_rds": ["py.typed", "*.pyi"],
        "types_aiobotocore_rds_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_redshift": ["py.typed", "*.pyi"],
        "types_aiobotocore_redshift_data": ["py.typed", "*.pyi"],
        "types_aiobotocore_redshift_serverless": ["py.typed", "*.pyi"],
        "types_aiobotocore_rekognition": ["py.typed", "*.pyi"],
        "types_aiobotocore_repostspace": ["py.typed", "*.pyi"],
        "types_aiobotocore_resiliencehub": ["py.typed", "*.pyi"],
        "types_aiobotocore_resource_explorer_2": ["py.typed", "*.pyi"],
        "types_aiobotocore_resource_groups": ["py.typed", "*.pyi"],
        "types_aiobotocore_resourcegroupstaggingapi": ["py.typed", "*.pyi"],
        "types_aiobotocore_robomaker": ["py.typed", "*.pyi"],
        "types_aiobotocore_rolesanywhere": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53_recovery_cluster": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53_recovery_control_config": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53_recovery_readiness": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53domains": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53profiles": ["py.typed", "*.pyi"],
        "types_aiobotocore_route53resolver": ["py.typed", "*.pyi"],
        "types_aiobotocore_rum": ["py.typed", "*.pyi"],
        "types_aiobotocore_s3": ["py.typed", "*.pyi"],
        "types_aiobotocore_s3control": ["py.typed", "*.pyi"],
        "types_aiobotocore_s3outposts": ["py.typed", "*.pyi"],
        "types_aiobotocore_s3tables": ["py.typed", "*.pyi"],
        "types_aiobotocore_s3vectors": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_a2i_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_edge": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_featurestore_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_geospatial": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_metrics": ["py.typed", "*.pyi"],
        "types_aiobotocore_sagemaker_runtime": ["py.typed", "*.pyi"],
        "types_aiobotocore_savingsplans": ["py.typed", "*.pyi"],
        "types_aiobotocore_scheduler": ["py.typed", "*.pyi"],
        "types_aiobotocore_schemas": ["py.typed", "*.pyi"],
        "types_aiobotocore_sdb": ["py.typed", "*.pyi"],
        "types_aiobotocore_secretsmanager": ["py.typed", "*.pyi"],
        "types_aiobotocore_security_ir": ["py.typed", "*.pyi"],
        "types_aiobotocore_securityhub": ["py.typed", "*.pyi"],
        "types_aiobotocore_securitylake": ["py.typed", "*.pyi"],
        "types_aiobotocore_serverlessrepo": ["py.typed", "*.pyi"],
        "types_aiobotocore_service_quotas": ["py.typed", "*.pyi"],
        "types_aiobotocore_servicecatalog": ["py.typed", "*.pyi"],
        "types_aiobotocore_servicecatalog_appregistry": ["py.typed", "*.pyi"],
        "types_aiobotocore_servicediscovery": ["py.typed", "*.pyi"],
        "types_aiobotocore_ses": ["py.typed", "*.pyi"],
        "types_aiobotocore_sesv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_shield": ["py.typed", "*.pyi"],
        "types_aiobotocore_signer": ["py.typed", "*.pyi"],
        "types_aiobotocore_simspaceweaver": ["py.typed", "*.pyi"],
        "types_aiobotocore_snow_device_management": ["py.typed", "*.pyi"],
        "types_aiobotocore_snowball": ["py.typed", "*.pyi"],
        "types_aiobotocore_sns": ["py.typed", "*.pyi"],
        "types_aiobotocore_socialmessaging": ["py.typed", "*.pyi"],
        "types_aiobotocore_sqs": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm_contacts": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm_guiconnect": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm_incidents": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm_quicksetup": ["py.typed", "*.pyi"],
        "types_aiobotocore_ssm_sap": ["py.typed", "*.pyi"],
        "types_aiobotocore_sso": ["py.typed", "*.pyi"],
        "types_aiobotocore_sso_admin": ["py.typed", "*.pyi"],
        "types_aiobotocore_sso_oidc": ["py.typed", "*.pyi"],
        "types_aiobotocore_stepfunctions": ["py.typed", "*.pyi"],
        "types_aiobotocore_storagegateway": ["py.typed", "*.pyi"],
        "types_aiobotocore_sts": ["py.typed", "*.pyi"],
        "types_aiobotocore_supplychain": ["py.typed", "*.pyi"],
        "types_aiobotocore_support": ["py.typed", "*.pyi"],
        "types_aiobotocore_support_app": ["py.typed", "*.pyi"],
        "types_aiobotocore_swf": ["py.typed", "*.pyi"],
        "types_aiobotocore_synthetics": ["py.typed", "*.pyi"],
        "types_aiobotocore_taxsettings": ["py.typed", "*.pyi"],
        "types_aiobotocore_textract": ["py.typed", "*.pyi"],
        "types_aiobotocore_timestream_influxdb": ["py.typed", "*.pyi"],
        "types_aiobotocore_timestream_query": ["py.typed", "*.pyi"],
        "types_aiobotocore_timestream_write": ["py.typed", "*.pyi"],
        "types_aiobotocore_tnb": ["py.typed", "*.pyi"],
        "types_aiobotocore_transcribe": ["py.typed", "*.pyi"],
        "types_aiobotocore_transfer": ["py.typed", "*.pyi"],
        "types_aiobotocore_translate": ["py.typed", "*.pyi"],
        "types_aiobotocore_trustedadvisor": ["py.typed", "*.pyi"],
        "types_aiobotocore_verifiedpermissions": ["py.typed", "*.pyi"],
        "types_aiobotocore_voice_id": ["py.typed", "*.pyi"],
        "types_aiobotocore_vpc_lattice": ["py.typed", "*.pyi"],
        "types_aiobotocore_waf": ["py.typed", "*.pyi"],
        "types_aiobotocore_waf_regional": ["py.typed", "*.pyi"],
        "types_aiobotocore_wafv2": ["py.typed", "*.pyi"],
        "types_aiobotocore_wellarchitected": ["py.typed", "*.pyi"],
        "types_aiobotocore_wisdom": ["py.typed", "*.pyi"],
        "types_aiobotocore_workdocs": ["py.typed", "*.pyi"],
        "types_aiobotocore_workmail": ["py.typed", "*.pyi"],
        "types_aiobotocore_workmailmessageflow": ["py.typed", "*.pyi"],
        "types_aiobotocore_workspaces": ["py.typed", "*.pyi"],
        "types_aiobotocore_workspaces_instances": ["py.typed", "*.pyi"],
        "types_aiobotocore_workspaces_thin_client": ["py.typed", "*.pyi"],
        "types_aiobotocore_workspaces_web": ["py.typed", "*.pyi"],
        "types_aiobotocore_xray": ["py.typed", "*.pyi"],
    },
    python_requires=">=3.8",
    project_urls={
        "Documentation": "https://youtype.github.io/types_aiobotocore_docs/",
        "Source": "https://github.com/youtype/mypy_boto3_builder",
        "Tracker": "https://github.com/youtype/mypy_boto3_builder/issues",
    },
    install_requires=['typing-extensions; python_version<"3.12"'],
    zip_safe=False,
)
