# (generated with --quick)

from typing import Any, Callable

def And(argument1, argument2) -> Callable[[], Any]: ...
def MimeTypeEquals(argument) -> Callable[[], Any]: ...
def NameEquals(argument) -> Callable[[], Any]: ...
