# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API Clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cardscan_client.models.eligibility_api_response_eligibility_request import EligibilityApiResponseEligibilityRequest

class TestEligibilityApiResponseEligibilityRequest(unittest.TestCase):
    """EligibilityApiResponseEligibilityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EligibilityApiResponseEligibilityRequest:
        """Test EligibilityApiResponseEligibilityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EligibilityApiResponseEligibilityRequest`
        """
        model = EligibilityApiResponseEligibilityRequest()
        if include_optional:
            return EligibilityApiResponseEligibilityRequest(
                control_number = '',
                trading_partner_service_id = '',
                provider = cardscan_client.models.eligibility_api_response_eligibility_request_provider.EligibilityApiResponse_eligibility_request_provider(
                    first_name = '', 
                    last_name = '', 
                    organization_name = '', 
                    npi = '', ),
                subscriber = cardscan_client.models.eligibility_api_response_eligibility_request_subscriber.EligibilityApiResponse_eligibility_request_subscriber(
                    first_name = '', 
                    last_name = '', 
                    member_id = '', 
                    date_of_birth = '', )
            )
        else:
            return EligibilityApiResponseEligibilityRequest(
        )
        """

    def testEligibilityApiResponseEligibilityRequest(self):
        """Test EligibilityApiResponseEligibilityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
