# coding: utf-8

"""
    CardScan API

    The official documentation for the CardScan API Clients.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cardscan_client.models.scan_metadata_capture_score_scores_inner import ScanMetadataCaptureScoreScoresInner

class TestScanMetadataCaptureScoreScoresInner(unittest.TestCase):
    """ScanMetadataCaptureScoreScoresInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanMetadataCaptureScoreScoresInner:
        """Test ScanMetadataCaptureScoreScoresInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanMetadataCaptureScoreScoresInner`
        """
        model = ScanMetadataCaptureScoreScoresInner()
        if include_optional:
            return ScanMetadataCaptureScoreScoresInner(
                score = 1.337,
                laplacian = 1.337
            )
        else:
            return ScanMetadataCaptureScoreScoresInner(
        )
        """

    def testScanMetadataCaptureScoreScoresInner(self):
        """Test ScanMetadataCaptureScoreScoresInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
