ENTITY_VARIABLE = "variable"
ENTITY_FUNCTION = "function"
ENTITY_CLASS = "class"

FLD_NAME = "name"
FLD_FUNCTIONS = "functions"
FLD_CLASSES = "classes"
FLD_PARAMETERS = "parameters"
FLD_DOCSTRING = "docstring"
FLD_BODY = "body"
FLD_RETURN = "return"
FLD_SUPERCLASSES = "superclasses"
FLD_ATTRIBUTES = "attributes"
FLD_METHODS = "methods"
