def matematika(x, amal, y):
    if amal == "+":
        return x + y
    elif amal == "-":
        return x - y
    elif amal == "*":
        return x * y
    elif amal == "/":
        return x / y