from _typeshed import Incomplete

class _APIClient:
    BASE_URL: str
    api_key: Incomplete
    headers: Incomplete
    def __init__(self, api_key) -> None: ...
    def get_hybrid_layer(self, user_query): ...
    def begin_conversation(self, user_choices, user_query, chosen_model_name): ...
    def send_additional_message(self, additional_message, assistant_id, thread_id): ...
    def end_conversation(self, assistant_id, thread_id): ...

class _MultiStepSelection:
    steps: Incomplete
    selections: Incomplete
    def __init__(self, steps) -> None: ...

def chat(user_query: Incomplete | None = None, api_key: Incomplete | None = None) -> None: ...
